% The next two lines are required to start off numbering
\pagenumbering{arabic}
\setcounter{page}{1}

\section{INTRODUCTION}

\subsection{CONTEXT FOR THE \Sexpr{assess.yr} ASSESSMENT}

Assessments of \Sexpr{fish.name} stocks in \Sexpr{bc} were done for \Sexpr{length(allRegionNames$major)} major stock assessment regions (SARs): \Sexpr{PasteNicely(allRegionNames$major)}.
We also present data for \Sexpr{length(allRegionNames$minor)} minor SARs: \Sexpr{PasteNicely(allRegionNames$minor)}.
Assessments for the five major \Sexpr{common.name} stocks areas are reported in the main body of this report, whereas assessments for the two minor stock areas are reported in Appendix \ref{chap:minors}. 
There are several key components to the management procedures of \Sexpr{fish.name} (\emph{\Sexpr{science.name}}) in BC.
Here we define a management procedure as the suite of activities that leads to catches in any given year.
These components include: which, and how much data are collected; what is assumed about stock structure, the stock assessment model used; and the \Sexpr{common.name} harvest control rule (HCR) that mathematically converts some estimate of current stock status to a total allowable catch (TAC) \citep{delamare1998} and implementation errors.
How well a particular management procedure performs depends on what objectives are defined for the management of the stock, including the probability of achieving target biomass level, the probability of avoiding limit biomass levels, the mean catch, the variability in catch and others.
Accordingly, the performance of any given management procedure cannot be viewed without understanding management objectives.

\Sexpr{fish.name}{} has been managed using a set harvest control rule but according to our definition above, the management procedure applied in practice has been in a constant state of flux.
Since it was implemented in 1986 and formally tested in \citet{hall1988}, there is no single element that has not changed: the survey data changed in \Sexpr{newSurvYr} to the dive survey; the harvest control rule changed from being applied to the current spawning biomass estimate to the projected spawning stock biomass estimate; and assessment model assumptions have changed on multiple occasions with different discrete and instantaneous formulations, alternative assumptions about \textit{q}, and others that included empirical weight at age and time-varying estimates of natural mortality; plus many others.
In addition to operational changes in the application of management procedures, there is some evidence for environmental and ecological changes that resulted in apparent changes in size at age and natural mortality that would have affected management procedure performance even if it had been consistently applied.
As a result, it is difficult to attribute departures from the original predictions of management procedure performance (in terms of probability of fisheries closures, average annual variability of catch) to any single cause.

This year's assessment presents two base cases assessments for each of the 5 major stocks: ``AM1'' denoting the case where surface (\Sexpr{min(yrRange)}--\Sexpr{newSurvYr-1}) and dive (\Sexpr{newSurvYr} -- \Sexpr{max(yrRange)}) survey catchability parameters ($q_1$ and $q_2$) are estimated using a prior distribution, and ``AM2'' denoting the case where the surface survey catchability ($q_1$) is estimated and the dive survey catchability is fixed at $q_2 = 1$.
The ISCAM modelling code used in \Sexpr{assess.yr} has been updated to the new platform, the detailes of which are described in the Bridging Analysis, Appendix \ref{chap:bridge}. 

Sensitivity cases for AM1 and AM2 investigate
(1) estimation of time-varying vs. constant natural mortality,
(2) errors-in-variables parameterization of process and observation error,
(3) sensitivity to broadening of the prior on \textit{q}, and
(4) juxtaposition of maturity-at-age and selectivity-at-age.
Sensitivity cases are presented for all 5 major stocks.

\subsection{LIFE HISTORY}

\Sexpr{fish.name} is a pelagic species migrating between inshore spawning and offshore feeding areas of the North Pacific.
In the eastern Pacific, \Sexpr{common.name} distribution ranges from California to the Beaufort Sea.
In southern BC, \Sexpr{common.name} recruit to the spawning stock and are sexually mature predominantly at age 3 with some precocious 2 year olds joining the spawning population.
In northern BC, \Sexpr{common.name} tend to spawn for the first time at ages 3 and 4 with few or no two year old recruits \citep{taylor1964}.
It is generally believed that in the Strait of Georgia the young-of-year \Sexpr{common.name} overwinter in their first year before joining the immature and adult populations in the offshore feeding grounds whereas in other areas of the coast young-of-year \Sexpr{common.name} appear to begin migration offshore at the end of their first summer \citep{hourston1980}.
\Sexpr{Common.name} mature and recruit to the spawning stock predominantly at age 3 within BC but age-at-recruitment tends to increase with latitude within this range.

\Sexpr{Common.name} are iteroparous and return to spawn each year once reaching maturity, until they die naturally or intercepted in fisheries.
Based on many years of tagging data it is evident that while \Sexpr{common.name} generally return to the same large geographical region each year they do not home to the same spawning beach or bay each year \citep{hay2001, flostrand2009}.
Each female produces about 20--40,000 eggs and quite consistently about 100 eggs/g of female weight with larger females producing more eggs than smaller and younger fish \citep{hourston1980, hay1985}.

The age of maturity of \Sexpr{common.name} is difficult to assess since few surveys of maturing fish have been conducted in the offshore areas.
Indications from histological assessment of developing ovaries suggests that about 25 percent of fish mature at age 2 and at least 90\% are mature at age 3 (D. Hay, unpublished data).
This is consistent with observations for southern BC stocks, as described above.

The majority of \Sexpr{common.name} in BC appear to occur as large schooling aggregations exhibiting seasonal migratory behaviour.
The main Haida Gwaii (HG) and Prince Rupert District (PRD) stocks feed in Hecate Strait during the summer and fall months, remaining in the offshore areas of Hecate Strait prior to inshore spawning migration in February before spawning in March through May.
The main Central Coast (CC) stock feeds in southern Hecate Strait and Queen Charlotte Sound during the summer and early fall months, remaining in offshore areas prior to inshore migration in February to the CC before spawning in March and April.
The main Strait of Georgia (SOG) stock feeds off the west coast of Vancouver Island during the summer and early fall months, reentering the SOG beginning in October before spawning in March and April.
The main west coast of Vancouver Island (WCVI) stock feeds in offshore areas of southern Vancouver Island during the summer and early fall months (mixing with the migratory SOG stock), returning inshore in late fall before spawning in March and April, with some early spawns occuring January and February.

\subsection{STOCK STRUCTURE}

Research examining stock structure of \Sexpr{fish.name} includes studies using genetics and a variety of tagging methods.
\citet{beacham2008} examined genetic population structure of \Sexpr{fish.name} in BC and adjacent regions using microsatellite variation.
This research identified four stocks of \Sexpr{fish.name} in BC, as well as stocks in southeast Alaska, Washington, and California.
In BC, differences in timing of spawning were identified as the main isolating mechanisms among stocks, although it is also recognized that geographic isolation of spawning populations may also have some effect in maintaining genetic distinctiveness among stocks.
The genetic research concludes that the limited genetic differentiation observed among \Sexpr{fish.name} populations in BC is consistent with among-population straying rates that are sufficient to homogenize allele frequencies over broad areas but \citet{beacham2008} also caution that while straying among \Sexpr{fish.name} populations in BC is sufficient to lead to minimal genetic differentiation among \Sexpr{fish.name} from different areas, the levels of straying may not be sufficient to offset overexploitation of the species in specific regions.
 
Beginning in the 1930s, BC \Sexpr{fish.name} have been the subject of three tag-recovery programs.
The first study employed internal belly tags (1936--1967),
the second external anchor tags (1979--1992),
and the third internal coded wire tags (1999--2006).
The most recent analysis of data collected from the coded wire tag program indicates a wide range in fidelity across regions, from 53 to 90\% \citep{flostrand2009}, consistent with previous findings by \citet{stevenson1954, hourston1982, ware2000, hay2001, ware2001}.

The stock concept for BC \Sexpr{common.name} has changed over time in response to the need for fisheries management.
In recent years, migratory stocks have been the target for the roe and food and bait fisheries although some resident stocks, usually found within inlets, are thought to also supported bait fisheries.
At present, for the purposes of fisheries management, BC \Sexpr{fish.name} stocks are managed as five major and two minor stock areas (Figure \ref{figBC}).
With the terms `major' and `minor' being used to describe relative differences in the geographic and biomass scales being represented by them.
Stock boundaries for major and minor stocks attempt to capture the habitat range of relatively discrete migratory \Sexpr{common.name} stocks, and are based on historical records of commercial catch and spawning locations.
Each stock assessment region (SAR) is comprised of several to many \Sexpr{common.name} Statistical Areas that are further broken down into \Sexpr{common.name} Sections and then Locations.
Maps identifying stock boundaries and Statistical Areas for each SAR can be found on
\href{http://www.pac.dfo-mpo.gc.ca/science/species-especes/pelagic-pelagique/herring-hareng/herspawn/pages/default0-eng.html}{the DFO website}.

\subsection{ECOSYSTEM CONSIDERATIONS}

As a forage species, \Sexpr{common.name} play a key role in the marine ecosystem and are a food source for a variety of species \citep{schweigert2010}.
\Sexpr{Common.name} are an important prey species to many piscivores including Pacific Salmon (Coho and Chinook), Pacific Hake, Pacific Halibut, Arrowtooth Flounder, and Spiny Dogfish.
They are also believed to be important in the diet of marine mammal predators such as Steller and California sea lions, harbour and northern fur seals, harbour porpoises, Pacific white-sided dolphins, humpback, and grey whales.
Over the time series depicted in the \Sexpr{fish.name} assessment (1951-2012), population sizes of seals and sea lions and baleen whales, which forage on \Sexpr{common.name}, have increased \citep{sealion2003, seal2010, caretta2011, crawford2011}.

DFO is currently compiling data to develop ecosystem modeling approaches in the hope that this endeavor (along with other ecosystem modeling initiatives at the University of British Columbia) will help explain how environmental and ecological interactions have affected BC \Sexpr{common.name} stocks, and how they are likely to be affected in the future.

In the meantime, DFO Pacific Region has committed to a Management Strategy Evaluation (MSE) process for \Sexpr{fish.name} within which the performance of management procedures in the face of ecosystem impacts on natural mortality and growth will be tested. Testing the performance of management procedures in the face such ecosystem changes for BC \Sexpr{common.name} stocks is a priority area of research for DFO.

\subsection{HERRING FISHERIES}

\Sexpr{Common.name} have been harvested for many years to provide a variety of food products.
First Nations have traditionally harvested whole \Sexpr{common.name} and \Sexpr{common.name} spawn for food, social and ceremonial (FSC) purposes.
The commercial \Sexpr{fish.name} fishery started in BC in the 19th century for the local food market, and quickly expanded into a dry salt fishery for the orient.
In 1937 a reduction fishery was also established to produce fishmeal and fish oil (Hourston and Haegele, 1980).
After the collapse of the Pacific Sardine in the late 1940s, \Sexpr{fish.name} became the major fishery off Canada's Pacific coast, and catches steadily increased to over 200,000 tonnes in the early 1960s (Beamish et al. 2004).

From the early 1930s to the late 1960s, \Sexpr{common.name} were commercially harvested and processed (reduced) into relatively low-value products such as fishmeal and oil.
Commercial catches increased dramatically in the early 1960s, but were unsustainable.
By 1965, most of the older fish had been removed from the spawning population by a combination of overfishing and by a sequence of weak year-classes attributed to unfavourable environmental conditions and a low spawning biomass.
As a result, the commercial fishery collapsed and was closed by the federal government in 1967 to rebuild the resource.
During the closure from 1967 to 1971, limited fishing activity occurred at low levels \citep{hourston1980b}.
At this time, there was a growing interest in harvesting roe \Sexpr{common.name} for export to Japan, where \Sexpr{common.name} stocks had been decimated.
A small experimental roe harvest began in 1971 and expanded rapidly until 1983, when a fixed harvest rate was introduced to regulate catch.
A series of above average year-classes occurred in the early 1970s, rapidly rebuilding stocks and permitting the re-opening of all areas for commercial fishing.

\subsection{MANAGEMENT OF MAJOR HERRING STOCKS}

The harvest rule for Pacific Herring is described as \citep{martell2012}:
\begin{equation} \label{eqHarvestRule}
U'_{T+1} = \begin{cases}
0 & SB_{T+1} \leq 0.25 \cdot \mli{SB}_0 \\
\text{min} \left( \frac{SB_{T+1} - 0.25 \cdot \mli{SB}_0}{B_{T+1}}, ~ 0.2 \right) & B_{T+1} > 0.25 \cdot \mli{SB}_0
\end{cases}
\end{equation}
where $T$ is the terminal year for the stock assessment, $SB_{T+1}$ is the prefishery forecast biomass in year $T+1$, and $\mli{SB}_0$ is the unfished equilibrium spawning stock biomass.
The output from the harvest control rule is the intended annual harvest rate, which is reduced to zero as the spawning stock is depleted to the level of $0.25\cdot\mli{SB}_0$.

For the major stock areas, the harvest control rule is a hybrid that combines both constant escapement and constant harvest rate policies, allowing for a reduced harvest rate in areas where the intended 20\% annual harvest rate would bring the forecast pre-fishery mature spawning biomass (i.e., the “escapement”) to levels below the cut-off value of $0.25\cdot\mli{SB}_0$ \citep {cleary2010}. 
This cut-off value was selected based on simulation work (Hall 1986, Hall et al. 1988, Zheng et al. 1993, Haist et al. 1993)  suggesting that for stocks above the $0.25\cdot\mli{SB}_0$ level, that the hybrid HCR would produce lower catch variance and fewer fishery closures than a constant escapement rule. 
The simulation work focussed on an analysis of stock dynamics for the SOG stock only.

Contrary to the predictions of the analyses done in the late 1980s, some \Sexpr{common.name} stocks appear to have been below cut-off levels relatively frequently.
Since 1986 there have been several different stock assessments models used, each of which had different assumptions and new data so that for each assessment, in each year, there were new estimates of current and unfished spawning biomass levels; it is therefore not possible to compare the current stock assessments estimates to what would have been estimated historically.
Accordingly, the best approximation that is available to determine if stocks were above or below cut-offs is to examine historical Integrated Fisheries Management Plans.
On the basis of this analysis, three of the major \Sexpr{common.name} stocks, WCVI, CC, and HG, were below cut-off for 32\%, 21\%, and 46\% of years, respectively from 1986 to 2013.
The relative contribution of harvest, environmental and ecological interactions causing changes in natural mortality and growth, or alternative assessment models (in particular more conservative models applied before 2011), and/or other factors to the stocks having been estimated to be below cut-offs is currently not well understood.

Since the introduction of the HCR for \Sexpr{fish.name} the policy environment for Canadian fisheries has changed with the introduction of the Sustainable Fisheries Framework in 2009 (www.dfo-mpo.gc.ca/fm-gp/pechesfisheries/fish-ren-peche/sff-cpd/overview-cadre-eng.htm) which includes the Fisheries Decision-making Framework incorporating the Precautionary Approach (www.dfo-mpo.gc.ca/fm-gp/peches-fisheries/fish-ren-peche/sff-cpd/precaution-eng.htm), hereafter called the DMF policy. 
The DMF policy is one component of the Sustainable Fisheries Framework, the Department's national strategy for moving DFO towards an ecosystem approach to management of Canadian fisheries. 
The 2017 Request for Scientific Information and Advice (RSIA) submitted by Fisheries Management has requested that advice for Pacific Herring be consistent with the DMF policy requirement to characterize uncertainty and risk.
DFO Pacific Region has committed to Renewal of the Management Framework for \Sexpr{fish.name}, including updated simulation analyses of harvest control rules. 
Although the \Sexpr{common.name} HCR was not originally designed to address the intent of the DMF policy, the form of the rule does meet the requirement to reduce the fishing rate as stock status declines to low levels of abundance, a tactic intended to encourage stock growth towards the target biomass reference point. 
Simulation analyses of HCR will occur within a Management Strategy Evaluation (MSE) process, focussing on establishing Management Procedures compliant with the DMF policy, including avoiding Limit Reference Points (LRP) with high probabiliy and establishing Upper Stock Reference (USR) points or target biomass levels.


\subsection{BIOLOGICAL REFERENCE POINTS}

[Use some text from the Rob's LRP paper?]

LRP
USR

The recently reviewed and approved CSAS publication "The Selection and Role of Limit Reference Points for Pacific Herring (\mli{Clupea pallasii}) in British Columbia, Canada" (\citep{kronlund2017}) is a significant and new contribution of research to the topic of biological reference points for \Sexpr{fish.name} and other forage species. 


\subsection{ASSESSMENT HISTORY}

[Placeholder]
