\section{INTRODUCTION}

\subsection{CONTEXT FOR THE \Sexpr{assess.yr} ASSESSMENT}

Assessments of \Sexpr{fish.name} stocks in \Sexpr{bc} were done for \Sexpr{length(allRegionNames$major)} major stock assessment regions (SARs): \Sexpr{PasteNicely(allRegionNames$major)}.
We also present data for \Sexpr{length(allRegionNames$minor)} minor SARs: \Sexpr{PasteNicely(allRegionNames$minor)}.
Assessments for the five major \Sexpr{common.name} stocks areas are reported in the main body of this report, whereas assessments for the two minor stock areas are reported in Appendix \ref{chap:minors}.
There are several key components to the management procedures of \Sexpr{fish.name} (\emph{\Sexpr{science.name}}) in BC.
Here we define a management procedure as the suite of activities that leads to catches in any given year.
These components include: 
which, and how much data are collected;
what is assumed about stock structure, the stock assessment model used; and
the \Sexpr{common.name} harvest control rule (HCR) that mathematically converts some estimate of current stock status to a total allowable catch (TAC) \citep{delamare1998} and implementation errors.
How well a particular management procedure performs depends on what objectives are defined for the management of the stock, including the probability of achieving target biomass level, the probability of avoiding limit biomass levels, the mean catch, the variability in catch and others.
Accordingly, the performance of any given management procedure cannot be viewed without understanding management objectives.

\Sexpr{fish.name}{} has been managed using a set harvest control rule but according to our definition above, the management procedure applied in practice has been in a constant state of flux.
Since it was implemented in 1986 and formally tested in \citet{hall1988}, there is no single element that has not changed:
the survey data changed in \Sexpr{newSurvYr} to the dive survey;
the harvest control rule changed from being applied to the current spawning biomass estimate to the projected spawning stock biomass estimate; and
assessment model assumptions have changed on multiple occasions with different discrete and instantaneous formulations, alternative assumptions about $q$, and others that included empirical weight at age and time-varying estimates of natural mortality;
plus many others.
In addition to operational changes in the application of management procedures, there is some evidence for environmental and ecological changes that resulted in apparent changes in size at age and natural mortality that would have affected management procedure performance even if it had been consistently applied.
As a result, it is difficult to attribute departures from the original predictions of management procedure performance (in terms of probability of fisheries closures, average annual variability of catch) to any single cause.

This year's assessment presents two base cases assessments for each of the 5 major stocks: ``AM1'' denoting the case where surface (\Sexpr{min(yrRange)}--\Sexpr{newSurvYr-1}) and dive (\Sexpr{newSurvYr}--\Sexpr{max(yrRange)}) survey catchability parameters ($q_1$ and $q_2$) are estimated using a prior distribution, and ``AM2'' denoting the case where the surface survey catchability ($q_1$) is estimated and the dive survey catchability is fixed at $q_2 = 1$.
The ISCAM modelling code used in \Sexpr{assess.yr} has been updated to the new platform, the detailes of which are described in the Bridging Analysis (Appendix \ref{chap:bridge}).

Sensitivity cases for \Sexpr{PasteNicely(mNames)} investigate:
\begin{resdoclist}
\item Estimation of time-varying vs. constant natural mortality,
\item Errors-in-variables parameterization of process and observation error,
\item Sensitivity to broadening of the prior on $q$, and
\item Juxtaposition of maturity-at-age and selectivity-at-age.
\end{resdoclist}
Sensitivity cases are presented for all \Sexpr{length(allRegions$major)} major stocks.

\subsection{LIFE HISTORY}\label{secLifeHist}

\Sexpr{fish.name} is a pelagic species migrating between inshore spawning and offshore feeding areas of the North Pacific.
In the eastern Pacific, \Sexpr{common.name} distribution ranges from California to the Beaufort Sea.
In southern BC, \Sexpr{common.name} recruit to the spawning stock and are sexually mature predominantly at age 3 with some precocious 2 year olds joining the spawning population.
In northern BC, \Sexpr{common.name} tend to spawn for the first time at ages 3 and 4 with few or no two year old recruits \citep{taylor1964}.
It is generally believed that in the Strait of Georgia the young-of-year \Sexpr{common.name} overwinter in their first year before joining the immature and adult populations in the offshore feeding grounds whereas in other areas of the coast young-of-year \Sexpr{common.name} appear to begin migration offshore at the end of their first summer \citep{hourston1980}.
\Sexpr{Common.name} mature and recruit to the spawning stock predominantly at age 3 within BC but age-at-recruitment tends to increase with latitude within this range.

\Sexpr{Common.name} are iteroparous and return to spawn each year once reaching maturity, until they die naturally or intercepted in fisheries.
Based on many years of tagging data it is evident that while \Sexpr{common.name} generally return to the same large geographical region each year they do not home to the same spawning beach or bay each year \citep{hay2001, flostrand2009}.
Each female produces about 20--40,000 eggs and quite consistently about 100 eggs/g of female weight, with larger females producing more eggs than smaller and younger fish \citep{hourston1980, hay1985}.

The age of maturity of \Sexpr{common.name} is difficult to assess since few surveys of maturing fish have been conducted in the offshore areas.
Indications from histological assessment of developing ovaries suggests that about 25\% of \Sexpr{fish.name} mature at age 2, and at least 90\% mature at age 3 (D. Hay, unpublished data).
This is consistent with observations for southern BC stocks, as described above.

The majority of \Sexpr{common.name} in BC appear to occur as large schooling aggregations exhibiting seasonal migratory behaviour.
The main Haida Gwaii (HG) and Prince Rupert District (PRD) stocks feed in Hecate Strait during the summer and fall months, remaining in the offshore areas of Hecate Strait prior to inshore spawning migration in February before spawning in March through May.
The main Central Coast (CC) stock feeds in southern Hecate Strait and Queen Charlotte Sound during the summer and early fall months, remaining in offshore areas prior to inshore migration in February to the CC before spawning in March and April.
The main Strait of Georgia (SOG) stock feeds off the west coast of Vancouver Island during the summer and early fall months, reentering the SOG beginning in October before spawning in March and April.
The main west coast of Vancouver Island (WCVI) stock feeds in offshore areas of southern Vancouver Island during the summer and early fall months (mixing with the migratory SOG stock), returning inshore in late fall before spawning in March and April, with some early spawns occuring January and February.

\subsection{STOCK STRUCTURE}

Research examining stock structure of \Sexpr{fish.name} includes studies using genetics and a variety of tagging methods.
\citet{beacham2008} examined genetic population structure of \Sexpr{fish.name} in BC and adjacent regions using microsatellite variation.
This research identified four stocks of \Sexpr{fish.name} in BC, as well as stocks in southeast Alaska, Washington, and California.
In BC, differences in timing of spawning were identified as the main isolating mechanisms among stocks, although it is also recognized that geographic isolation of spawning populations may also have some effect in maintaining genetic distinctiveness among stocks.
The genetic research concludes that the limited genetic differentiation observed among \Sexpr{fish.name} populations in BC is consistent with among-population straying rates that are sufficient to homogenize allele frequencies over broad areas but \citet{beacham2008} also caution that while straying among \Sexpr{fish.name} populations in BC is sufficient to lead to minimal genetic differentiation among \Sexpr{fish.name} from different areas, the levels of straying may not be sufficient to offset overexploitation of the species in specific regions.

Beginning in the 1930s, BC \Sexpr{fish.name} have been the subject of three tag-recovery programs.
The first study employed internal belly tags (1936--1967),
the second external anchor tags (1979--1992),
and the third internal coded wire tags (1999--2006).
The most recent analysis of data collected from the coded wire tag program indicates a wide range in fidelity across regions, from 53 to 90\% \citep{flostrand2009}, consistent with previous findings by \citet{stevenson1954, hourston1982, ware2000, hay2001, ware2001}.

The stock concept for BC \Sexpr{common.name} has changed over time in response to the need for fisheries management.
In recent years, migratory stocks have been the target for the roe and food and bait fisheries although some resident stocks, usually found within inlets, are thought to also supported bait fisheries.
At present, for the purposes of fisheries management, BC \Sexpr{fish.name} stocks are managed as five major and two minor stock areas (Figure \ref{figBC}).
With the terms `major' and `minor' being used to describe relative differences in the geographic and biomass scales being represented by them.
Stock boundaries for major and minor stocks attempt to capture the habitat range of relatively discrete migratory \Sexpr{common.name} stocks, and are based on historical records of commercial catch and spawning locations.
Each stock assessment region (SAR) is comprised of several to many \Sexpr{common.name} Statistical Areas that are further broken down into \Sexpr{common.name} Sections and then Locations.
Maps identifying stock boundaries and Statistical Areas for each SAR can be found on
\href{http://www.pac.dfo-mpo.gc.ca/science/species-especes/pelagic-pelagique/herring-hareng/herspawn/pages/default0-eng.html}{the DFO website}.

\subsection{ECOSYSTEM CONSIDERATIONS}

As a forage species, \Sexpr{common.name} play a key role in the marine ecosystem and are a food source for a variety of species \citep{schweigert2010}.
\Sexpr{Common.name} are an important prey species to many piscivores including Pacific Salmon (Coho and Chinook), Pacific Hake, Pacific Halibut, Arrowtooth Flounder, and Spiny Dogfish.
They are also believed to be important in the diet of marine mammal predators such as Steller and California sea lions, harbour and northern fur seals, harbour porpoises, Pacific white-sided dolphins, humpback, and grey whales.
Over the time series depicted in the \Sexpr{fish.name} assessment (1951-2012), population sizes of seals and sea lions and baleen whales, which forage on \Sexpr{common.name}, have increased \citep{sealion2003, seal2010, caretta2011, crawford2011}.

DFO is currently compiling data to develop ecosystem modeling approaches in the hope that this endeavor (along with other ecosystem modeling initiatives at the University of British Columbia) will help explain how environmental and ecological interactions have affected BC \Sexpr{common.name} stocks, and how they are likely to be affected in the future.

In the meantime, DFO Pacific Region has committed to a Management Strategy Evaluation (MSE) process for \Sexpr{fish.name} within which the performance of management procedures in the face of ecosystem impacts on natural mortality and growth will be tested.
Testing the performance of management procedures in the face such ecosystem changes for BC \Sexpr{common.name} stocks is a priority area of research for DFO.

\subsection{HERRING FISHERIES}

\Sexpr{Common.name} have been harvested for many years to provide a variety of food products.
First Nations have traditionally harvested whole \Sexpr{common.name} and \Sexpr{common.name} spawn for food, social and ceremonial (FSC) purposes.
The commercial \Sexpr{fish.name} fishery started in BC in the 19th century for the local food market, and quickly expanded into a dry salt fishery for the orient.
In 1937 a reduction fishery was also established to produce fishmeal and fish oil \citep{hourston1980}.
After the collapse of the Pacific Sardine in the late 1940s, \Sexpr{fish.name} became the major fishery off Canada's Pacific coast, and catches steadily increased to over 200,000 tonnes in the early 1960s \citep{beamish2004}.

From the early 1930s to the late 1960s, \Sexpr{common.name} were commercially harvested and processed (reduced) into relatively low-value products such as fishmeal and oil.
Commercial catches increased dramatically in the early 1960s, but were unsustainable.
By 1965, most of the older fish had been removed from the spawning population by a combination of overfishing and by a sequence of weak year-classes attributed to unfavourable environmental conditions and a low spawning biomass.
As a result, the commercial fishery collapsed and was closed by the federal government in 1967 to rebuild the resource.
During the closure from 1967 to 1971, limited fishing activity occurred at low levels \citep{hourston1980b}.
At this time, there was a growing interest in harvesting roe \Sexpr{common.name} for export to Japan, where \Sexpr{common.name} stocks had been decimated.
A small experimental roe harvest began in 1971 and expanded rapidly until 1983, when a fixed harvest rate was introduced to regulate catch.
A series of above average year-classes occurred in the early 1970s, rapidly rebuilding stocks and permitting the re-opening of all areas for commercial fishing.

\subsection{MANAGEMENT OF MAJOR HERRING STOCKS}\label{secMgmtMajorStocks}

The harvest rule for Pacific Herring is described as \citep{martell2011}:
\begin{equation} \label{eqHarvestRule}
U'_{T+1} = \begin{cases}
0 & SB_{T+1} \leq 0.25 \cdot \mli{SB}_0 \\
\text{min} \left( \frac{SB_{T+1} - 0.25 \cdot \mli{SB}_0}{B_{T+1}}, ~ 0.2 \right) & B_{T+1} > 0.25 \cdot \mli{SB}_0
\end{cases}
\end{equation}
where $T$ is the terminal year for the stock assessment, $\mli{SB}_{T+1}$ is the prefishery forecast biomass in year $T+1$, and $\mli{SB}_0$ is the unfished equilibrium spawning stock biomass.
The output from the harvest control rule is the intended annual harvest rate, which is reduced to zero as the spawning stock is depleted to the level of $0.25\cdot\mli{SB}_0$.

For the major stock areas, the harvest control rule is a hybrid that combines both constant escapement and constant harvest rate policies, allowing for a reduced harvest rate in areas where the intended 20\% annual harvest rate would bring the forecast pre-fishery mature spawning biomass (i.e., the `escapement') to levels below the cut-off value of $0.25\cdot\mli{SB}_0$ \citep{cleary2010,cleary2012}.

This cut-off value was selected based on simulation work \citep{hall1986, hall1988, zheng1993, haist1993}  suggesting that for stocks above the $0.25\cdot\mli{SB}_0$ level, that the hybrid HCR would produce lower catch variance and fewer fishery closures than a constant escapement rule.
The simulation work focussed on an analysis of stock dynamics for the SOG stock only.

Contrary to the predictions of the analyses done in the late 1980s, some \Sexpr{common.name} stocks appear to have been below cut-off levels relatively frequently.
Since 1986 there have been several different stock assessments models used, each of which had different assumptions and new data so that for each assessment, in each year, there were new estimates of current and unfished spawning biomass levels; it is therefore not possible to compare the current stock assessments estimates to what would have been estimated historically.
Accordingly, the best approximation that is available to determine if stocks were above or below cut-offs is to examine historical Integrated Fisheries Management Plans.
On the basis of this analysis, three of the major \Sexpr{common.name} stocks, WCVI, CC, and HG, were below cut-off for 32\%, 21\%, and 46\% of years, respectively from 1986 to 2013.
The relative contribution of harvest, environmental and ecological interactions causing changes in natural mortality and growth, or alternative assessment models (in particular more conservative models applied before 2011), and/or other factors to the stocks having been estimated to be below cut-offs is currently not well understood.

Since the introduction of the HCR for \Sexpr{fish.name} the policy environment for Canadian fisheries has changed with the introduction of the \href{http://www.dfo-mpo.gc.ca/reports-rapports/regs/sff-cpd/overview-cadre-eng.htm}{sustainable fisheries framework} in 2009 which includes a \href{http://www.dfo-mpo.gc.ca/reports-rapports/regs/sff-cpd/precaution-eng.htm}{fisheries decision-making framework incorporating the precautionary approach}, hereafter called the DFO PA Framework.
The DMF policy is one component of the Sustainable Fisheries Framework, the Department's national strategy for moving DFO towards an ecosystem approach to management of Canadian fisheries.
The 2017 Request for Scientific Information and Advice (RSIA) submitted by Fisheries Management has requested that advice for Pacific Herring be consistent with the DMF policy requirement to characterize uncertainty and risk.
DFO Pacific Region has committed to Renewal of the Management Framework for \Sexpr{fish.name}, including updated simulation analyses of harvest control rules.
Although the \Sexpr{common.name} HCR was not originally designed to address the intent of the DMF policy, the form of the rule does meet the requirement to reduce the fishing rate as stock status declines to low levels of abundance, a tactic intended to encourage stock growth towards the target biomass reference point.
Simulation analyses of HCR will occur within a Management Strategy Evaluation (MSE) process, focussing on establishing Management Procedures compliant with the DMF policy, including avoiding Limit Reference Points (LRP) with high probabiliy and establishing Upper Stock Reference (USR) points or target biomass levels.

\subsection{BIOLOGICAL REFERENCE POINTS}

Unfished equilibrium spawning biomass ($\mli{SB}_0$) has been part of the management procedure for Pacific Herring since 1986 when $0.25\cdot\mli{SB}_0$ was adopted as a commercial fishing threshold (cut-off) in the harvest control rule. 
Annual science advice includes presentation of estimated stock status relative to the long-term average unfished spawning biomass, and presentation of probabilistic decision tables with projected pre-fishery biomass relative to fractions of $\mli{SB}_0$ (e.g., $0.25\cdot\mli{SB}_0$ and $0.30\cdot\mli{SB}_0$).
Time series estimates of weight-at-age show significant declines in mean weight-at-age for all major stocks between 1980-2010 as well as increasing and decreasing trends in estimated natural mortality.
Given these nonstationary dynamics $\mli{SB}_0$ is calculated using on long-term average weight-at-age and average natural mortality and we do not present dynamic estimates of $\mli{SB}_0$, i.e., based on shorter time series or during ``high'' or ``low'' productivivity periods.
Regarding the calculation of reference points, the DFO PA Framework recommends ``as long as a time series as possible should be used in establishing reference points for a stock''.
Many stocks will show substantial variation in productivity over a long time series, and this variation should be taken into account when setting the reference points." 

Evidence of nonstationarity as well as modelling of three selectivity types due to concurrent harvesting by multiple gear types limits our ability to calculate and evaluate equilibrium reference points such as $B_\text{MSY}$ in the management procedure.
Previous attempts to estimate $B_\text{MSY}$ for BC Pacific Herring stocks has resulted in unusually high estimates of $F_\text{MSY}$ \citep{martell2011}.

Attempts to estimate $F_\text{MSY}$ using ISCAM are presented in \ref{secMatAge} of the Sensitivity Analyses, based on a single gear type (roe seine), in order to investigate whether overlap or lack of overlap in maturity and selectivity curves impacts estimates of  $F_\text{MSY}$.  %SH to check this statement (is single gear correct?)

\subsubsection{Limit Reference Point}

The recently reviewed and approved CSAS publication ``The Selection and Role of Limit Reference Points for Pacific Herring (\emph{Clupea pallasii}) in British Columbia, Canada'' \citep{kronlund2017} is a significant and new contribution of research to the topic of biological reference points for \Sexpr{fish.name} and other forage species.
The DFO PA Framework specifies that a Limit Reference Point (LRP) should be positioned before a state of serious harm occurs, rather than at the state of serious harm and that it must be avoided with high probability.
\citet{kronlund2017} use an evidence-based production analysis conditional on current data and stock assessment model assumptions, to evaluate whether the major \Sexpr{fish.name} stocks in British Columbia show stock states consistent with signs of possible serious harm.
The production analysis identified recent persistent states of low production and low biomass (LP-LB states) for the Central Coast (CC), Haida Gwaii (HG) and West Coast of Vancouver Island (WCVI) management areas.
The outcome of the research and the review meeting support for the recommended spawning biomass-based LRP of $0.30\cdot\mli{SB}_0$ for the CC, HG, and WCVI stocks based on results of the production analysis and consistency with international best practice recommendations.
Persistent LP-LB states were not diagnosed for stocks in the Prince Rupert District (PRD) and Strait of Georgia (SOG) management areas, however a LRP of $0.30\cdot\mli{SB}_0$ is also recommended for the PRD and SOG stocks as it aligns with best practice recommendations, and because these stocks are geographically adjacent to stocks for which recent low LP-LB states were detected.

The authors recommend the phasing-in of any new management procedure (i.e., changes to data collection, stock assessment models and/or harvest control rules) designed to avoid LRPs and achieve targets in order to mitigate short-term consequences to resource users.
Specific recommendations on \emph{how to} apply LRPs in the context of annual advice derived from stock assessment models were beyond the scope of the paper.
However as requested in the Terms of Reference, this assessment presents current estimates of spawning biomass for each major stock relative to the LRP.

\subsubsection{Upper Stock Reference}

A fully specified set of objectives that includes both LRPs and target reference points (TRPs) will be necessary to meet goals for renewal of the \Sexpr{fish.name} management system and consistency with the DFO PA Framework.
The Framework also defines the Upper Stock Reference (USR) point as the boundary between the Cautious and Healthy zones.
The Framework presents a special case where the USR and point where the harvest rate is reduced with declining stock status are equivalent (Figure \ref{figDFOPA}).
A more general representation distinguishes between biological reference points that represent limits and targets, and the points at which management action is taken to avoid limits and achieve targets, typically represented by a harvest control rule \citep[e.g.,][]{kronlund2017}.
The USR and TRP can be equivalent, and the TRP cannot be lower than the USR.
The USR must be set at an appropriate distance above the LRP to provide sufficient opportunity for the management system to recognize a declining stock status through feedback in response to management actions.
The management actions are expressed by a management procedure that includes a choice of data, the stock assessment model, and catch recommendation generated by the harvest control rule. 

While the Framework defines the USR as the boundary between the Cautious and Healthy zones, it does not provide guidance on how to identify an appropriate choice of the breakpoint between these zones. 

The hybrid constant escapement/onstant harvest rate feature of the herring HCR was intended to maintain a minimum escapement level equal to the commercial fishery cut-off.
In this case, the management procedure has treated the LRP as an operational control point (OCP) where management action is taken.
In the design of the HCR, this ``ramp-down'' of the harvest rate is intended to avoid commercial fishery closures and encourage stock growth, however the reduction from $0.31\mli{SB}_0$ to $0.25\mli{SB}_0$ is so steep that there is a very limited range of estimated biomass where reduced harvest rates might arrest stock decline before closure of the commercial fisheries.
The effect of this feature of the HCR is the ``on or of'' behaviour seen in the simulation results of Cox et al. (2015),%
\footnote{Cox, S.P., Benson, A.J., Cleary, J.S., and Taylor, N.G. 2015. Candidate limit reference points as a basis for choosing among alternate harvest control rules for Pacific Herring (Clupea pallasii) in British Columbia. CSAS Working Paper 2013PEL01 (Accepted WP, final revisions stage).}
and \citet{herring2015}.
The outcome of which is that for 3 of the stocks, spawning biomass fell below this level far more often than predicted (Section \ref{secMgmtMajorStocks}). 

A comprehensive review of approaches to establishing both limit and target reference points for herring stocks worldwide for clupeids is included in \citet[][Appendix F]{kronlund2017}.
Examples for establishing the USR include:
\begin{resdoclist}
\item Interim USRs were defined at biomass levels to which stocks are expected to grow under average recruitment \citep{dfo2005}; recommended for Southern Gulf of St. Lawrence Atlantic Herring,
\item	The USR, referred to as $B_\text{BUF}$, is defined as the lowest observed historical spawning-stock biomass which produced good recruitment; recommended for West coast of Newfoundland (NAFO Div 4R) Atlantic Herring \citep{mcquinn1999}, and
\item	The biological limit, $B_\text{lim}$ is established as the minimum spawning stock biomass that would ensure adequate recruitment based on available stock-recruitment information, and the $B_\text{pa}$, the precautionary level for stock biomass, is set at 5.0 million tonnes which is $2\times$ the $B_\text{lim}$ of 2.5 million tonnes; recommended for Norwegian spring-spawning herring \citep{tjelmeland2009}.
\end{resdoclist}
In these examples, the biological references points are implemented as the lower and upper operational control points (OCPs) in a hockey-stick shaped harvest control rule.

For Canadian fisheries in the Maritimes Region, a commonly used approach to defining the USR (and the boundary between the cautious and healthy zones) is to set the USR equal to $2\times$ the LRP.
The following model-based approaches are used \citep{dfo2012}: 
\begin{resdoclist}[resume*]
\item Set the LRP at 40\% of spawning stock biomass at maximum sustainable yield ($\mli{SSB}_\text{MSY}$) and the USR at 80\% of ($\mli{SSB}_\text{MSY}$); recommended for 3NOPs4VWX+5 Atlantic Halibut, 4VsW Atlantic Cod, 4X5Y Haddock, 4VWX American Plaice,
\item LRP established based on analysis of stock-recruitment data, with proposed USR equal to $2\times$ the LRP; recommended for 4X5Y Atlantic Cod, and
\item	Reference points based on analysis of carrying capacity: LRP at 25\% of carrying capacity and USR at 50\% of carrying capacity; recommended for 4VWX Snow Crab. 
\end{resdoclist}
Where model-based estimates were not available, empirical approaches to approximating $B_\text{MSY}$ are used, with LRP and USR set at 40\% and 80\% of $B_\text{MSY}$ \citep{dfo2012}. 
However, estimates of MSY-statistics are not plausible for Pacific Herring in BC for reasons discussed by \citet{kronlund2017}.

\citet{Sinclair-Starr:2005} suggest using the long-term average biomass $B_\text{avg}$ as a proxy USR.
This approach of defining a historical target reference point is recommended for Rock Sole \citep{holt2016} and for Pacific cod \citep{forrest2015}.
An alternative to using the long-term average biomass is the average biomass during a productive period ($B_\text{avg-prod}$). 

Proposed candidate USR for \Sexpr{fish.name} are:
\begin{resdoclist}
\item	USR = long-term average spawning biomass $\mli{SB}_\text{avg}$,
\item	USR = long-term average biomass during a productive period $\mli{SB}_\text{avg-prod}$,
\item	USR = $2\times$ LRP (e.g., $0.60\mli{SB}_0$), and
\item	USR = $\mli{SB}_0$. 
\end{resdoclist}
The analysis conducted by \citet{kronlund2017} looked at a variety of $B_\text{MSY}$ proxies and they were rejected as implausible, thus we are not including $B_\text{MSY}$-based candidates at this time. 

Simulation testing of the consequences of the choice of LRP, USR, and TRP relative to candidate management procedures is the recommended procedure for understanding expected performance trade-offs in management outcomes.
The management outcomes are related to measurable objectives of avoiding LRPs with high probability and maintaining stocks at TRP levels with the desired probability over a specified time-frame appropriate to life history and current understanding of stock dynamics.
The DFO has committed to a management strategy evaluation process for \Sexpr{fish.name}, with engagement of managers and resource-users, focusing on evaluation of reference points and management procedures to fully align the \Sexpr{fish.name} management framework with the DFO PA Framework \citep{dfo09}.

\subsection{ASSESSMENT HISTORY}\label{secAssessHist}

Annual stock assessments for the BC Pacific Herring major stocks have been conducted using a catch-age model since the mid-2000s \citep{haist2006}. 
Since then, the design of the model has undergone re-structuring various model components, as often as every 2-3 years, to address issues identified during peer-review.
One major change introduced in 2011 \citep{martell2011} was setting the model to estimate the spawn dive survey scaling parameter $q_2$, rather than setting it fixed at $q_2=1.0$, as was done in previous assessment models. 
Another major change introduced in 2011 was to make the fishery cut-offs in the harvest control rule dependent on the model’s most recent estimate of unfished spawning biomass $\mli{SB}_0$ (i.e., cease fishing when the stock is estimated to be below $0.25\cdot\mli{SB}_0$). 
In previous model iterations, the fishery cut-offs were fixed at absolute biomass levels based on 1996 estimates of $0.25\cdot\mli{SB}_0$ \citep{schweigert1997}.  
Throughout this document, the term Assessment Model 1 (AM1) describes the more recent management procedure (MP), which estimates the scaling factor for the surface survey $q_1$ (1951-1987) and dive survey $q_2$ (1988-2017) using informative priors; and uses estimated fishery cut-offs.
Assessment Model 2 (AM2) refers to an approximation of the historical MP, in which the surface survey $q_1$ (1951-1987) is estimated, the dive survey $q_2$ (1988-2017) is fixed at 1.0 and the fishery cut-offs are fixed at 1996 levels.
There have been a number of requests to evaluate the potential consequences of applying AM1 vs. AM2 using simulation modelling. 
This reflects concerns that the consequences of applying AM1 were not simulation-tested prior to its implementation in 2011, which, along with lack of rebuilding in some areas, has led to questioning the performance of AM1.
Both MPs have been peer reviewed through CSAS and both have been implemented in the provision of science advice for Pacific Herring in previous years. 

To address concerns arising both from previous CSAS processes and from implementation of each approach, the 2016 Science Response \citep{herring2016} includes a table developed by the Herring Technical Working Group (HTWG) that describes the main attributes and limitations of AM1 and AM2, to support short-term decision-making \citep[see][Table A.1]{herring2016}.
The status of BC herring stocks in 2017 and forecasts for 2018 are provided in the form of dual stock assessment updates, using the AM1 \citep{martell2011} and AM2 \citep[approximation of][]{cleary2012} MPs.

% 0.8$B_\textMSY}$
% $q_1$
% $q_2$
% $0.25B_0$
% $\mli{SB}_0$
