\section{FIGURES}

% DFO precautionary approach  zones
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{maindoc/figures/DFOPA.png}
\caption{Zones in the Fisheries and Oceans Canada's precautionary approach paradigm.}
\label{figDFOPA}
\end{figure}

% Map of BC
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{maindoc/figures/BC.png}
\caption{Boundaries for the \Sexpr{fish.name} stock assessment regions (SARs) in \Sexpr{bc}.
The major SARs are \Sexpr{PasteNicely(allRegionNames$major)}.
The minor SARs are \Sexpr{PasteNicely(allRegionNames$minor)}.
Units: kilometres (km).}
\label{figBC}
\end{figure}

% Catch
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{\Sexpr{locOutput}Catch.png}
\caption{Time series of total landed catch in thousands of metric tonnes ($\text{t} \times 10^{3}$) of \Sexpr{fish.name} from \Sexpr{min(yrRange)} to \Sexpr{assess.yr} in the major stock assessment regions (SARs).}
\label{figCatch}
\end{figure}

% Weight-at-age
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{\Sexpr{locOutput}WeightAge.png}
\caption{Time series of weight-at-age in kilograms (kg) for age-\Sexpr{ageShow} (circles) and \Sexpr{nRoll}-year running mean weight-at-age (lines) for \Sexpr{fish.name} from \Sexpr{min(yrRange)} to \Sexpr{assess.yr} in the major stock assessment regions (SARs).
Lines show \Sexpr{nRoll}-year running means for age-\Sexpr{min(ageRange)} to age-\Sexpr{max(ageRange)} herring (incrementing higher from the lowest line); the thick black line highlights age-\Sexpr{ageShow} herring.
Missing weight-at-age values (i.e., years where there are no biological samples) are imputed using one of two methods: missing values at the beginning of the time series are imputed by extending the first non-missing value backwards; other missing values are imputed as the mean of the previous \Sexpr{nRoll} years.
\seineSamples{}
\plusGroup{}}
\label{figWeightAge}
\end{figure}

% Proportion-at-age
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{\Sexpr{locOutput}ProportionAge.png}
\caption{Time series of proportion-at-age for \Sexpr{fish.name} from \Sexpr{min(yrRange)} to \Sexpr{assess.yr} in the major stock assessment regions (SARs).
\seineSamples{}
\plusGroupProp{}}
\label{figProportionAge}
\end{figure}

% Number aged
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{\Sexpr{locOutput}NumberAged.png}
\caption{Number of biological samples by year for \Sexpr{fish.name} from \Sexpr{min(yrRange)} to \Sexpr{assess.yr} in the major stock assessment regions (SARs).
\seineSamples{}}
\label{figNumberAged}
\end{figure}

% Spawn index
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{\Sexpr{locOutput}SpawnIndex.png}
\caption{Time series of spawn index in thousands of metric tonnes ($\text{t} \times 10^{3}$) for \Sexpr{fish.name} from \Sexpr{min(yrRange)} to \Sexpr{assess.yr} in the major stock assessment regions (SARs).
\qPeriods{}
\spawnIndex{}}
\label{figSpawnIndex}
\end{figure}

% Start a loop over stocks for storyboard
\foreach \x in {\Sexpr{paste(allRegions$major, sep=",")}} {
% Start a loop over models for storyboard
\foreach \y in {\Sexpr{paste(mNames, sep=",")}} {
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{\Sexpr{locOutput}\x/Storyboard\y.png}
\caption{Model output for \Sexpr{fish.name} in the \x{} major stock assessment region (SAR) for \y.
Panel (a): model fit to time series of scaled spawn survey data in thousands of metric tonnes ($\text{t} \times 10^{3})$.
\qPeriods{}
The spawn survey data (i.e., spawn index) is scaled to abundance via the spawn survey scaling parameter $q$.
%: surface survey spawn index scaling parameter $q_{1} = \Sexpr{qVals$q1$AM2}$; and dive survey spawn index scaling parameter $q_{2} = \Sexpr{qVals$q2$AM2}$.
Panel (b): reconstructed number of age-\Sexpr{ageRec} recruits in millions.
Circles with vertical lines indicate medians and \Sexpr{ciLevel*100}\% credible intervals, respectively.
Panel (c): posterior estimates of instantaneous natural mortality.
Line and shaded area indicate the median and \Sexpr{ciLevel*100}\% credible interval, respectively.
Panel (d): posterior estimate of spawning biomass ($\mli{SB}_{t}$) for each year $t$ in thousands of metric tonnes ($\text{t} \times 10^{3}$).
Line and shaded area indicate median and \Sexpr{ciLevel*100}\% credible interval, respectively.
%unfished biomass ($\mli{SB}_0$) at far left, and
Also shown is projected spawning biomass assuming no fishing ($\mli{SB}_{\Sexpr{max(yrRange)+1}}$) at the far right: the circle and vertical line indicates the median and \Sexpr{ciLevel*100}\% credible interval, respectively.
Time series of vertical lines indicates commercial catch, excluding spawn on kelp (SOK).}
\label{figStoryboard\y\x}
\end{figure}
} % End loop over models for storyboard
} % End loop over stocks for storyboard

% Start a loop over stocks for production
\foreach \x in {\Sexpr{paste(allRegions$major, sep=",")}} {
% Start a loop over models for production
\foreach \y in {\Sexpr{paste(mNames, sep=",")}} {
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{\Sexpr{locOutput}\x/Production\y.png}
\caption{Production analysis for \Sexpr{fish.name} in the \x{} major stock assessment region (SAR) for \y.
Panel (a): time series of estimated spawning biomass (circles) and catch (vertical bars).
The lower \Sexpr{quantSSB*100}\% of spawning biomass estimates are shaded grey.
Reference lines are shown at estimates of $0.1B_0$, (red dashed line) $0.25B_0$ (blue dashed line), $0.3B_0$ (green dashed line), the 1996 fixed cutoff value (thick blue long dashed line), and unfished spawning biomass (solid blue line).
Panel (b): time series of estimated natural mortality.
Panels (c \& d): phase plots of spawning biomass production and spawning biomass production rate against spawning biomass, respectively, for the Dive survey period, from \Sexpr{newSurvYr} (black circle) to \Sexpr{max(yrRange)-1} (black diamond).
Grey shading of the circles becomes darker in chronological order.
Calendar years are indicated above each symbol.
The axis scales at the top of panels (c \& d) are in units of spawning biomass depletion (i.e., spawn biomass divided by the estimated unfished spawning biomass from the assessment model).
Reference lines in panel (c) are the same as those in panel (a).
All estimates quantities are based on maximum likelihood estimates (DFO 2016).}
\label{figProduction\y\x}
\end{figure}
} % End loop over models for production
} % End loop over stocks for production

% Effective harvest rate
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{\Sexpr{locOutput}/HarvestRate.png}
\caption{Effective harvest rate for \Sexpr{fish.name} in the major stock assessment regions (SARs) for models \Sexpr{PasteNicely(mNames)}.
Effective harvest rate in year t, $U_\text{t}$ is calculated as $U_\text{t} = \frac{C_\text{t}}{\mli{SB}_\text{t} + C_\text{t}}$ where $C_\text{t}$ is catch in year t, and $\mli{SB}_\text{t}$ is estimated spawning biomass in year t.
Black lines indicate medians and shaded ribbons indicate \Sexpr{ciLevel*100}\% confidence intervals for spawning biomass, $\mli{SB}_\text{t}$.
Horizontal dashed lines indicate $U_\text{t} = \Sexpr{intendU}$.}
\label{figHarvestRate}
\end{figure}

% Current biomass and LRP
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{\Sexpr{locOutput}/CurrentSSB.png}
\caption{Estimated spawning biomass in \Sexpr{max(yrRange)}, $\mli{SB}_{\Sexpr{max(yrRange)}}$ in thousands of tonnes, t for \Sexpr{fish.name} in the major stock assessment regions (SARs) for models \Sexpr{PasteNicely(mNames)}.
Vertical black lines indicate medians (solid) and \Sexpr{ciLevel*100}\% confidence intervals (dashed) for $\mli{SB}_{\Sexpr{max(yrRange)}}$.
Vertical red lines indicate medians, and shaded red rectangles indicate \Sexpr{ciLevel*100}\% confidence intervals for the limit reference point (LRP), $0.3\mli{SB}_0$, where $\mli{SB}_0$ is estimated unfished biomass.}
\label{figCurrentSSB}
\end{figure}

% Beverton-Holt stock-recruitment relationsip
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{\Sexpr{locOutput}/BevertonHolt.png}
\caption{Beverton-Holt stock-recruitment relationship using MPD estimates for \Sexpr{fish.name} in the major stock assessment regions (SARs) for model \Sexpr{mNames[1]}.
\darkThisYr{}
Lines indicate MPD Beverton-Holt stock-recruitment relationships.
Triangles indicate MPD estimates of unfished spawning biomass, $\mli{SB}_0$, and unfished age-\Sexpr{ageRec} recruitment, $R_0$.
Legend: tonnes (t).}
\label{figBevertonHolt}
\end{figure}


% %%------------------------------------------------------------------------------
% %% AGE COMPOSITION PLOTS (DATA ONLY)
% 
% \begin{figure}[H]
% \begin{center}
% <<agecomps-trawl, fig.height=5, fig.width=8>>=
% make.age.comp.plot(base.model,
%                    ind = 1,
%                    type = 1)
% @
% \end{center}
% %\vspace{0mm}
% \caption{Age composition data for the Reference Case for the commercial trawl
%   fishery. Blue points represent zero samples.}
% \label{fig:agecomps-trawl}
% \end{figure}
% %%------------------------------------------------------------------------------
% 
% \begin{figure}[H]
% \begin{center}
% <<agecomps-surveys, fig.height=9, fig.width=8>>=
% old.par <- par(no.readonly = TRUE)
% layout(matrix(c(1, 2, 3, 0),
%               2,
%               2,
%               byrow = TRUE))
% make.age.comp.plot(base.model,
%                    ind = 2,
%                    type = 1,
%                    ind.letter = "a")
% make.age.comp.plot(base.model,
%                    ind = 4,
%                    type = 1,
%                    ind.letter = "b")
% make.age.comp.plot(base.model,
%                    ind = 5,
%                    type = 1,
%                    ind.letter = "c")
% par(old.par)
% @
% \end{center}
% \caption{Age composition data for the Reference Case for the surveys (a) QCSSS,
%   (b) HSSS, and (c) WCVISS. Blue points represent zero samples.}
% \label{fig:agecomps-surveys}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% LENGTH BOXPLOTS
% \begin{figure}[H]
% \begin{center}
% <<lengthsubfleet, fig.height=9, fig.width=8>>=
% old.par <- par(no.readonly = TRUE)
% ylim <- c(20, 90)
% layout(matrix(c(1, 2, 3, 4),
%               2,
%               2,
%               byrow = TRUE))
% make.length.plot(trawl.bio,
%                  start.yr = 2005,
%                  sex = 2,
%                  plot.subfleet = TRUE,
%                  y.lim = ylim,
%                  add = TRUE,
%                  ind.letter = "a")
% make.length.plot(trawl.bio,
%                  start.yr = 2005,
%                  sex = 2,
%                  plot.subfleet = FALSE,
%                  y.lim = ylim,
%                  add = TRUE,
%                  ind.letter = "b")
% make.length.plot(trawl.bio,
%                  start.yr = 2005,
%                  sex = 1,
%                  plot.subfleet = TRUE,
%                  y.lim = ylim,
%                  add = TRUE,
%                  ind.letter = "c")
% make.length.plot(trawl.bio,
%                  start.yr = 2005,
%                  sex = 1,
%                  plot.subfleet = FALSE,
%                  y.lim = ylim,
%                  add = TRUE,
%                  ind.letter = "d")
% par(old.par)
% @
% \end{center}
% \caption{Length quantiles (2.5\textsuperscript{th}, 50\textsuperscript{th}, and
%   97.5\textsuperscript{th} percentiles) from samples taken on freezer trawler
%   vessels (a and c) and shoreside vessels (b and d) for females (a and b) and
%   males (c and d).}
% \label{fig:lengthsubfleet}
% \end{figure}
% %%------------------------------------------------------------------------------
% 
% %%------------------------------------------------------------------------------
% %% HARVEST CONTROL RULE ILLUSTRATION PLOT
% \begin{figure}[H]
% \begin{center}
% <<hcrillustration, fig.height=5, fig.width=8>>=
% make.hcr.plot()
% @
% \end{center}
% \caption{Illustration of a harvest control rule consistent with the
%   Precautionary Approach for a hypothetical stock. The biomass-based
%   reference points are shown as vertical dotted lines. The limit removal
%   rate is shown as a horizontal blue line. In this illustration, biomass
%   (unspecified units) is shown on the bottom axis. LRP = Limit Reference Point;
%   USR = Upper Stock Reference; LRR = Limit Removal Rate. See \citet{dfo09}
%   for more detail.}
% \label{fig:hcrillustration}
% \end{figure}
%
%%------------------------------------------------------------------------------
%% MCMC Priors/posteriors plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.priors>>=
make.priors.posts.plot(hg.b, priors.only = FALSE)
@
\end{center}
\caption{Prior probability distributions (lines) with comparative posterior
  histograms (bars) used in the Haida Gwaii AM2 model. Parameters $q_k$
  represent gears where: $k=1$ is the surface survey and $k=2$ is the dive
  survey. The dotted red lines are the MPD estimates.}
\label{fig:hg-priors}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<prd.priors>>=
make.priors.posts.plot(pr.b, priors.only = FALSE)
@
\end{center}
\caption{Prior probability distributions (lines) with comparative posterior
  histograms (bars) used in the Prince Rupert District AM2 model. Parameters $q_k$
  represent gears where: $k=1$ is the surface survey and $k=2$ is the dive
  survey. The dotted red lines are the MPD estimates.}
\label{fig:prd-priors}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<cc.priors>>=
make.priors.posts.plot(cc.b, priors.only = FALSE)
@
\end{center}
\caption{Prior probability distributions (lines) with comparative posterior
  histograms (bars) used in the Central Coast AM2 model. Parameters $q_k$
  represent gears where: $k=1$ is the surface survey and $k=2$ is the dive
  survey. The dotted red lines are the MPD estimates.}
\label{fig:cc-priors}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<sog.priors>>=
make.priors.posts.plot(sog.b, priors.only = FALSE)
@
\end{center}
\caption{Prior probability distributions (lines) with comparative posterior
  histograms (bars) used in the Strait of Georgia AM2 model. Parameters $q_k$
  represent gears where: $k=1$ is the surface survey and $k=2$ is the dive
  survey. The dotted red lines are the MPD estimates.}
\label{fig:sog-priors}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<wcvi.priors>>=
make.priors.posts.plot(wcvi.b, priors.only = FALSE)
@
\end{center}
\caption{Prior probability distributions (lines) with comparative posterior
  histograms (bars) used in the WCVI AM2 model. Parameters $q_k$
  represent gears where: $k=1$ is the surface survey and $k=2$ is the dive
  survey. The dotted red lines are the MPD estimates.}
\label{fig:wcvi-priors}
\end{figure}
%%------------------------------------------------------------------------------
%% MCMC Trace plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.traces, fig.height=8, fig.width=8>>=
make.traces.plot(hg.b, axis.lab.freq = 200)
@
\end{center}
\caption{Trace plots for MCMC output of estimated parameters for the Haida Gwaii
  AM2 model. The MCMC run had chain length \Sexpr{mcmc.length}, with
  a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
  The catchability parameter $q_1$ represents the surface survey and $q_2$
  the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
  $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
  follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
\label{fig:hg-traces}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<prd.traces, fig.height=8, fig.width=8>>=
make.traces.plot(pr.b, axis.lab.freq = 200)
@
\end{center}
\caption{Trace plots for MCMC output of estimated parameters for the Prince
  Rupert District AM2 model. The MCMC run had chain length \Sexpr{mcmc.length},
  with a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
  The catchability parameter $q_1$ represents the surface survey and $q_2$
  the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
  $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
  follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
\label{fig:prd-traces}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<cc.traces, fig.height=8, fig.width=8>>=
make.traces.plot(cc.b, axis.lab.freq = 200)
@
\end{center}
\caption{Trace plots for MCMC output of estimated parameters for the Central
  Coast AM2 model. The MCMC run had chain length \Sexpr{mcmc.length}, with
  a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
  The catchability parameter $q_1$ represents the surface survey and $q_2$
  the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
  $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
  follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
\label{fig:cc-traces}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<sog.traces, fig.height=8, fig.width=8>>=
make.traces.plot(sog.b, axis.lab.freq = 200)
@
\end{center}
\caption{Trace plots for MCMC output of estimated parameters for the Strait of
  Georgia AM2 model. The MCMC run had chain length \Sexpr{mcmc.length}, with
  a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
  The catchability parameter $q_1$ represents the surface survey and $q_2$
  the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
  $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
  follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
\label{fig:sog-traces}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<wcvi.traces, fig.height=8, fig.width=8>>=
make.traces.plot(wcvi.b, axis.lab.freq = 200)
@
\end{center}
\caption{Trace plots for MCMC output of estimated parameters for the WCVI
  AM2 model. The MCMC run had chain length \Sexpr{mcmc.length}, with
  a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
  The catchability parameter $q_1$ represents the surface survey and $q_2$
  the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
  $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
  follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
\label{fig:wcvi-traces}
\end{figure}
%%------------------------------------------------------------------------------
%% Autocorrelation plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg-autocor, fig.height=8, fig.width=8>>=
make.autocor.plot(hg.b)
@
\end{center}
\caption{Autocorrelation plots for MCMC output of estimated parameters for the
  Haida Gwaii AM2 model. See Figure~\ref{fig:hg-traces} for parameter
  descriptions.}
\label{fig:hg-autocor}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<prd-autocor, fig.height=8, fig.width=8>>=
make.autocor.plot(pr.b)
@
\end{center}
\caption{Autocorrelation plots for MCMC output of estimated parameters for the
  Prince Rupert District AM2 model. See Figure~\ref{fig:prd-traces} for parameter
  descriptions.}
\label{fig:prd-autocor}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<cc-autocor, fig.height=8, fig.width=8>>=
make.autocor.plot(cc.b)
@
\end{center}
\caption{Autocorrelation plots for MCMC output of estimated parameters for the
  Central Coast AM2 model. See Figure~\ref{fig:cc-traces} for parameter
  descriptions.}
\label{fig:cc-autocor}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<sog-autocor, fig.height=8, fig.width=8>>=
make.autocor.plot(sog.b)
@
\end{center}
\caption{Autocorrelation plots for MCMC output of estimated parameters for the
  Strait of Georgia AM2 model. See Figure~\ref{fig:sog-traces} for parameter
  descriptions.}
\label{fig:sog-autocor}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<wcvi-autocor, fig.height=8, fig.width=8>>=
make.autocor.plot(wcvi.b)
@
\end{center}
\caption{Autocorrelation plots for MCMC output of estimated parameters for the
  WCVI AM2 model. See Figure~\ref{fig:wcvi-traces} for parameter
  descriptions.}
\label{fig:wcvi-autocor}
\end{figure}
%%------------------------------------------------------------------------------
%% MCMC Pairs plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg-pairs, fig.height=8, fig.width=8>>=
make.pairs.plot(hg.b)
@
\end{center}
\caption{Pairs plots for MCMC output of estimated parameters in for the Haida
  Gwaii AM2 model. See Figure~\ref{fig:hg-traces} for parameter descriptions.}
\label{fig:hg-pairs}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<prd-pairs, fig.height=8, fig.width=8>>=
make.pairs.plot(pr.b)
@
\end{center}
\caption{Pairs plots for MCMC output of estimated parameters in for the Prince
  Rupert AM2 model. See Figure~\ref{fig:prd-traces} for parameter descriptions.}
\label{fig:prd-pairs}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<cc-pairs, fig.height=8, fig.width=8>>=
make.pairs.plot(cc.b)
@
\end{center}
\caption{Pairs plots for MCMC output of estimated parameters in for the Central
  Coast AM2 model. See Figure~\ref{fig:cc-traces} for parameter descriptions.}
\label{fig:cc-pairs}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<sog-pairs, fig.height=8, fig.width=8>>=
make.pairs.plot(sog.b)
@
\end{center}
\caption{Pairs plots for MCMC output of estimated parameters in for the Strait
  of Georgia AM2 model. See Figure~\ref{fig:sog-traces} for parameter
  descriptions.}
\label{fig:sog-pairs}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<wcvi-pairs, fig.height=8, fig.width=8>>=
make.pairs.plot(wcvi.b)
@
\end{center}
\caption{Pairs plots for MCMC output of estimated parameters in for the WCVI
  AM2 model. See Figure~\ref{fig:wcvi-traces} for parameter descriptions.}
\label{fig:wcvi-pairs}
\end{figure}
%%------------------------------------------------------------------------------
%% Selectivity plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.selex, fig.height=5,fig.width=8>>=
make.selex.comparison.plot(hg.b, gear.names, leg = "bottomright")
@
\end{center}
\caption{Estimated and Fixed selectivities for the Haida Gwaii AM2 model.}
\label{fig:hg-selex}
%\end{figure}
%%------------------------------------------------------------------------------
%\begin{figure}[H]
\begin{center}
<<prd.selex, fig.height=5,fig.width=8>>=
make.selex.comparison.plot(pr.b, gear.names, leg = "bottomright")
@
\end{center}
\caption{Estimated and Fixed selectivities for the Prince Rupert District model.}
\label{fig:prd-selex}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<cc.selex, fig.height=5,fig.width=8>>=
make.selex.comparison.plot(cc.b, gear.names, leg = "bottomright")
@
\end{center}
\caption{Estimated and Fixed selectivities for the Central Coast AM2 model.}
\label{fig:cc-selex}
%\end{figure}
%%------------------------------------------------------------------------------
%\begin{figure}[H]
\begin{center}
<<sog.selex, fig.height=5,fig.width=8>>=
make.selex.comparison.plot(sog.b, gear.names, leg = "bottomright")
@
\end{center}
\caption{Estimated and Fixed selectivities for the Strait of Georgia AM2 model.}
\label{fig:sog-selex}
\end{figure}
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<wcvi.selex, fig.height=5,fig.width=8>>=
make.selex.comparison.plot(wcvi.b, gear.names, leg = "bottomright")
@
\end{center}
\caption{Estimated and Fixed selectivities for the WCVI AM2 model.}
\label{fig:wcvi-selex}
\end{figure}
%%------------------------------------------------------------------------------

%%------------------------------------------------------------------------------
%% Sensitivity plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.index.surface.fit>>=
leg.names <- c("AM1 Constant M",
               "AM1 Time-varying M",
               "AM2 Constant M",
               "AM2 Time-varying M")
make.index.fit.plot(list(hg.am1.constm,
                         hg.am1.tvm,
                         hg.am2.constm,
                         hg.am2.tvm),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 1,
                    leg = "topright",
                    model.names = leg.names,
                    ylim = c(0, 60))
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model index fits (lines) and inputs
  (points) for the Haida Gwaii surface survey.}
\label{fig:hg-index-surface-fit}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<hg.index.dive.fit>>=
make.index.fit.plot(list(hg.am1.constm,
                         hg.am1.tvm,
                         hg.am2.constm,
                         hg.am2.tvm),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 2,
                    leg = "topleft",
                    model.names = leg.names,
                    ylim = c(0, 60))
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model index fits (lines) and inputs
  (points) for the Haida Gwaii dive survey.}
\label{fig:hg-index-dive-fit}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<prd.index.surface.fit>>=
make.index.fit.plot(list(pr.am1.constm,
                         pr.am1.tvm,
                         pr.am2.constm,
                         pr.am2.tvm),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 1,
                    leg = "topright",
                    model.names = leg.names,
                    ylim = c(0, 60))
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model index fits (lines) and inputs
  (points) for the Prince Rupert District
  surface survey.}
\label{fig:prd-index-surface-fit}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<prd.index.dive.fit>>=
make.index.fit.plot(list(pr.am1.constm,
                         pr.am1.tvm,
                         pr.am2.constm,
                         pr.am2.tvm),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 2,
                    leg = "topleft",
                    model.names = leg.names,
                    ylim = c(0, 60))
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model index fits (lines) and inputs
  (points) for the Prince Rupert District
  dive survey.}
\label{fig:prd-index-dive-fit}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<cc.index.surface.fit>>=
make.index.fit.plot(list(cc.am1.constm,
                         cc.am1.tvm,
                         cc.am2.constm,
                         cc.am2.tvm),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 1,
                    leg = "topright",
                    model.names = leg.names,
                    ylim = c(0, 60))
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model index fits (lines) and inputs
  (points) for the Central Coast surface survey.}
\label{fig:cc-index-surface-fit}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<cc.index.dive.fit>>=
make.index.fit.plot(list(cc.am1.constm,
                         cc.am1.tvm,
                         cc.am2.constm,
                         cc.am2.tvm),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 2,
                    leg = "topleft",
                    model.names = leg.names,
                    ylim = c(0, 60))
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model index fits (lines) and inputs
  (points) for the Central Coast
  dive survey.}
\label{fig:cc-index-dive-fit}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<sog.index.surface.fit>>=
make.index.fit.plot(list(sog.am1.constm,
                         sog.am1.tvm,
                         sog.am2.constm,
                         sog.am2.tvm),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 1,
                    leg = "topright",
                    model.names = leg.names,
                    ylim = c(0, 220))
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model index fits (lines) and inputs
  (points) for the Strait of Georgia
  surface survey.}
\label{fig:sog-index-surface-fit}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<sog.index.dive.fit>>=
make.index.fit.plot(list(sog.am1.constm,
                         sog.am1.tvm,
                         sog.am2.constm,
                         sog.am2.tvm),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 2,
                    leg = "topleft",
                    model.names = leg.names,
                    ylim = c(0, 220))
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model index fits (lines) and inputs
  (points) for the Strait of Georgia
  dive survey.}
\label{fig:sog-index-dive-fit}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<wcvi.index.surface.fit>>=
make.index.fit.plot(list(wcvi.am1.constm,
                         wcvi.am1.tvm,
                         wcvi.am2.constm,
                         wcvi.am2.tvm),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 1,
                    leg = "topright",
                    model.names = leg.names,
                    ylim = c(0, 150))
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model index fits (lines) and inputs
  (points) for the WCVI
  surface survey.}
\label{fig:wcvi-index-surface-fit}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<wcvi.index.dive.fit>>=
make.index.fit.plot(list(wcvi.am1.constm,
                         wcvi.am1.tvm,
                         wcvi.am2.constm,
                         wcvi.am2.tvm),
                    start.yr = 1950,
                    end.yr = 2016,
                    ind = 2,
                    leg = "topleft",
                    model.names = leg.names,
                    ylim = c(0, 150))
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model index fits (lines) and inputs
  (points) for the WCVI
  dive survey.}
\label{fig:wcvi-index-dive-fit}
\end{figure}
%%------------------------------------------------------------------------------
%% Sensitivity to M biomass plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.biomass.m>>=
make.biomass.mcmc.plot(list(hg.am1.constm,
                            hg.am1.tvm,
                            hg.am2.constm,
                            hg.am2.tvm),
                    model.names = leg.names,
                    ylim = c(0, 250),
                    leg = "topright",
                    show.bo.line = FALSE)
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model biomass trajectories
  for the Haida Gwaii stock.}
\label{fig:hg-biomass-m}
\end{figure}
%%------------------------------------------------------------------------------

%\begin{figure}[H]
%\begin{center}
%<<prd.biomass.m>>=
%make.biomass.mcmc.plot(list(pr.b,
                           % pr.am1.tvm,
                           % pr.am2.constm,
                           % pr.am2.tvm),
                   % model.names = leg.names,
                   % ylim = c(0, 120),
                   % leg = "topright",
                   % show.bo.line = TRUE)
%@
%\end{center}
%\caption{Natural mortality sensitivity model biomass trajectories
%  for the Prince Rupert District stock.}
%\label{fig:prd-biomass-m}
%\end{figure}
%%------------------------------------------------------------------------------

%\begin{figure}[H]
%\begin{center}
%<<cc.biomass.m>>=
%make.biomass.mcmc.plot(list(cc.am1.constm,
                            %cc.am1.tvm,
                           % cc.am2.constm,
                           % cc.am2.tvm),
                    %model.names = leg.names,
                    %ylim = c(0, 150),
                    %leg = "topright",
                    %show.bo.line = TRUE)
%@
%\end{center}
%\caption{Natural mortality sensitivity model biomass trajectories
  %for the Central Coast stock.}
%\label{fig:prd-biomass-m}
%\end{figure}
%%------------------------------------------------------------------------------

%\begin{figure}[H]
%\begin{center}
%<<sog.biomass.m>>=
%make.biomass.mcmc.plot(list(sog.am1.constm,
%                            sog.am1.tvm,
%                           sog.am2.constm,
 %                           sog.am2.tvm),
%                    model.names = leg.names,
%                    ylim = c(0, 350),
%                    leg = "topright",
%                   show.bo.line = TRUE)
%@
%\end{center}
%\caption{Natural mortality sensitivity model biomass trajectories
%  for the Strait of Georgia stock.}
%\label{fig:sog-biomass-m}
%\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<wcvi.biomass.m>>=
make.biomass.mcmc.plot(list(wcvi.am1.constm,
                            wcvi.am1.tvm,
                            wcvi.am2.constm,
                            wcvi.am2.tvm),
                    model.names = leg.names,
                    ylim = c(0, 250),
                    leg = "topright",
                    show.bo.line = FALSE)
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model biomass trajectories
  for the WCVI stock.}
\label{fig:wcvi-biomass-m}
\end{figure}
%%------------------------------------------------------------------------------
%% Sensitivity to M recruitment deviation plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.recdevs.m>>=
make.recr.mcmc.plot(list(hg.am1.constm,
                         hg.am1.tvm,
                         hg.am2.constm,
                         hg.am2.tvm),
                    model.names = leg.names,
                    type = 2,
                    offset = 0.1,
                    ylim = c(-4, 4),
                    leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model recruitment deviations
  for the Haida Gwaii stock.}
\label{fig:hg-recdevs-m}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<prd.recdevs.m>>=
make.recr.mcmc.plot(list(pr.am1.constm,
                         pr.am1.tvm,
                         pr.am2.constm,
                         pr.am2.tvm),
                    model.names = leg.names,
                    type = 2,
                    offset = 0.1,
                    ylim = c(-4, 4),
                    leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model recruitment deviations
  for the Prince Rupert District stock.}
\label{fig:prd-recdevs-m}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<cc.recdevs.m>>=
make.recr.mcmc.plot(list(cc.am1.constm,
                         cc.am1.tvm,
                         cc.am2.constm,
                         cc.am2.tvm),
                    model.names = leg.names,
                    type = 2,
                    offset = 0.1,
                    ylim = c(-4, 4),
                    leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model recruitment deviations
  for the Central Coast stock.}
\label{fig:cc-recdevs-m}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<sog.recdevs.m>>=
make.recr.mcmc.plot(list(sog.am1.constm,
                         sog.am1.tvm,
                         sog.am2.constm,
                         sog.am2.tvm),
                    model.names = leg.names,
                    type = 2,
                    offset = 0.1,
                    ylim = c(-4, 4),
                    leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model recruitment deviations
  for the Strait of Georgia stock.}
\label{fig:sog-recdevs-m}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<wcvi.recdevs.m>>=
make.recr.mcmc.plot(list(wcvi.am1.constm,
                         wcvi.am1.tvm,
                         wcvi.am2.constm,
                         wcvi.am2.tvm),
                    model.names = leg.names,
                    type = 2,
                    offset = 0.1,
                    ylim = c(-4, 4),
                    leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity model recruitment deviations
  for the WCVI stock.}
\label{fig:wcvi-recdevs-m}
\end{figure}

%%------------------------------------------------------------------------------
%% Sensitivity to M Natural mortality plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.m>>=
make.natural.mort.mcmc.plot(list(hg.am1.constm,
                                 hg.am1.tvm,
                                 hg.am2.constm,
                                 hg.am2.tvm),
                                 model.names = leg.names,
                                 which.gear = 1,
                                 ylim = c(0,2),
                                 leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality for the sensitivity to the natural mortality parameter
  for the Haida Gwaii stock.}
\label{fig:hg-m}
\end{figure}

%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<prd.m>>=
make.natural.mort.mcmc.plot(list(pr.am1.constm,
                                 pr.am1.tvm,
                                 pr.am2.constm,
                                 pr.am2.tvm),
                                 model.names = leg.names,
                                 which.gear = 1,
                                 ylim = c(0,1),
                                 leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality for the sensitivity to the natural mortality parameter
  for the Prince Rupert District stock.}
\label{fig:prd-m}
\end{figure}

%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<cc.m>>=
make.natural.mort.mcmc.plot(list(cc.am1.constm,
                                 cc.am1.tvm,
                                 cc.am2.constm,
                                 cc.am2.tvm),
                                 model.names = leg.names,
                                 which.gear = 1,
                                 ylim = c(0,2),
                                 leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality for the sensitivity to the natural mortality parameter
  for the Central Coast stock.}
\label{fig:cc-m}
\end{figure}

\begin{figure}[H]
\begin{center}
<<sog.m>>=
make.natural.mort.mcmc.plot(list(sog.am1.constm,
                                 sog.am1.tvm,
                                 sog.am2.constm,
                                 sog.am2.tvm),
                                 model.names = leg.names,
                                 which.gear = 1,
                                 ylim = c(0,2),
                                 leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality for the sensitivity to the natural mortality parameter
  for the Strait of Georgia stock.}
\label{fig:sog-m}
\end{figure}

%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<wcvi.m>>=
make.natural.mort.mcmc.plot(list(wcvi.am1.constm,
                                 wcvi.am1.tvm,
                                 wcvi.am2.constm,
                                 wcvi.am2.tvm),
                                 model.names = leg.names,
                                 which.gear = 1,
                                 ylim = c(0,2),
                                 leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality for the sensitivity to the natural mortality parameter
  for the WCVI stock.}
\label{fig:wcvi-m}
\end{figure}

%%------------------------------------------------------------------------------
%% Sensitivity to M number at age 2 plots
%%------------------------------------------------------------------------------
%\begin{figure}[H]
%\begin{center}
%<<hg.nage2.m>>=
%make.nage2.plot(list(hg.am1.constm,
%                     hg.am1.tvm,
%                     hg.am2.constm,
%                     hg.am2.tvm),
%                model.names = leg.names,
%                ylim = c(0,5000),
%                leg = "topright")
%@
%\end{center}
%\caption{Natural mortality sensitivity models number at age 2
 % (in millions) for the Haida Gwaii stock.}
%\label{fig:hg-nage2-m}
%\end{figure}
%%------------------------------------------------------------------------------

%\begin{figure}[H]
%\begin{center}
%<<prd.nage2.m>>=
%make.nage2.plot(list(pr.am1.constm,
%                     pr.am1.tvm,
%                     pr.am2.constm,
%                     pr.am2.tvm),
%                model.names = leg.names,
%                ylim = c(0,3000),
%                leg = "topright")
%@
%\end{center}
%\caption{Natural mortality sensitivity models number at age 2
 % (in millions) for the Prince Rupert stock.}
%\label{fig:pr-nage2-m}
%\end{figure}
%%------------------------------------------------------------------------------

%\begin{figure}[H]
%\begin{center}
%<<cc.nage2.m>>=
%make.nage2.plot(list(cc.am1.constm,
%                     cc.am1.tvm,
%                     cc.am2.constm,
%                     cc.am2.tvm),
%                model.names = leg.names,
%                ylim = c(0,2500),
%                leg = "topright")
%@
%\end{center}
%\caption{Natural mortality sensitivity models number at age 2
%  (in millions) for the Central Coast stock.}
%\label{fig:cc-nage2-m}
%\end{figure}
%%------------------------------------------------------------------------------

%\begin{figure}[H]
%\begin{center}
%<<sog.nage2.m>>=
%make.nage2.plot(list(sog.am1.constm,
%                     sog.am1.tvm,
%                     sog.am2.constm,
%                     sog.am2.tvm),
%                model.names = leg.names,
%                ylim = c(0,8000),
%                leg = "topleft")
%@
%\end{center}
%\caption{Natural mortality sensitivity models number at age 2
%  (in millions) for the Strait of Georgia stock.}
%\label{fig:sog-nage2-m}
%\end{figure}
%%------------------------------------------------------------------------------

%\begin{figure}[H]
%\begin{center}
%<<wcvi.nage2.m>>=
%make.nage2.plot(list(wcvi.am1.constm,
%                     wcvi.am1.tvm,
%                     wcvi.am2.constm,
%                     wcvi.am2.tvm),
%                model.names = leg.names,
%                ylim = c(0,5000),
%                leg = "topright")
%@
%\end{center}
%\caption{Natural mortality sensitivity models number at age 2
%  (in millions) for the WCVI stock.}
%\label{fig:wcvi-nage2-m}
%\end{figure}
%%------------------------------------------------------------------------------
%% Sensitivity to M survey q priors
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.q.m>>=
make.q.plot(list(hg.am1.constm,
                 hg.am1.tvm,
                 hg.am2.constm,
                 hg.am2.tvm),
            model.names = leg.names,
            ylim = c(0,2),
            leg = "topleft")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity models survey q
  for the Haida Gwaii stock.}
\label{fig:hg-q-m}
\end{figure}
%%------------------------------------------------------------------------------

%\begin{figure}[H]
%\begin{center}
%<<prd.q.m>>=
%make.q.plot(list(pr.am1.constm,
%                 pr.am1.tvm,
%                 pr.am2.constm,
%                 pr.am2.tvm),
%            model.names = leg.names,
%            ylim = c(0,2),
%            leg = "topleft")
%@
%\end{center}
%\caption{Natural mortality sensitivity models survey q
 % for the Prince Rupert District stock.}
%\label{fig:hg-pr-m}
%\end{figure}
%%------------------------------------------------------------------------------

%\begin{figure}[H]
%\begin{center}
%<<cc.q.m>>=
%make.q.plot(list(cc.am1.constm,
%                 cc.am1.tvm,
%                 cc.am2.constm,
%                cc.am2.tvm),
%            model.names = leg.names,
%            ylim = c(0,2),
%            leg = "topleft")
%@
%\end{center}
%\caption{Natural mortality sensitivity models survey q
 % for the Central Coast stock.}
%\label{fig:cc-q-m}
%\end{figure}
%%------------------------------------------------------------------------------

%\begin{figure}[H]
%\begin{center}
%<<sog.q.m>>=
%make.q.plot(list(sog.am1.constm,
%                 sog.am1.tvm,
%                 sog.am2.constm,
%                 sog.am2.tvm),
%            model.names = leg.names,
%            ylim = c(0,2),
%            leg = "topright")
%@
%\end{center}
%\caption{Natural mortality sensitivity models survey q
%  for the Strait of Georgia stock.}
%\label{fig:sog-q-m}
%\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<wcvi.q.m>>=
make.q.plot(list(wcvi.am1.constm,
                 wcvi.am1.tvm,
                 wcvi.am2.constm,
                 wcvi.am2.tvm),
            model.names = leg.names,
            ylim = c(0,2),
            leg = "topright")
@
\end{center}
\caption{Natural Mortality Sensitivity Case: Natural mortality sensitivity models survey q
  for the WCVI stock.}
\label{fig:wcvi-q-m}
\end{figure}

%%------------------------------------------------------------------------------
%% Sensitivity to M MCMC diagnostic plots - AM2
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.constm.priors>>=
make.priors.posts.plot(hg.am2.constm, priors.only = FALSE)
@
\end{center}
\caption{Prior probability distributions (lines) with comparative posterior
  histograms (bars) used in the Haida Gwaii AM2 model with constant natural
  mortality. Parameters $q_k$ represent gears where: $k=1$ is the surface
  survey and $k=2$ is the dive survey. The dotted red lines are the MPD
  estimates.}
\label{fig:hg-constm-priors}
\end{figure}

\begin{figure}[H]
\begin{center}
<<hg.constm.traces, fig.height=8, fig.width=8>>=
make.traces.plot(hg.am2.constm, axis.lab.freq = 200)
@
\end{center}
\caption{Trace plots for MCMC output of estimated parameters for the Haida Gwaii
  AM2 model with constant natural mortality. The MCMC run had chain length
  \Sexpr{mcmc.length}, with
  a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
  The catchability parameter $q_1$ represents the surface survey and $q_2$
  the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
  $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
  follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
\label{fig:hg-constm-traces}
\end{figure}

\begin{figure}[H]
\begin{center}
<<hg-constm-pairs, fig.height=8, fig.width=8>>=
make.pairs.plot(hg.am2.constm)
@
\end{center}
\caption{Pairs plots for MCMC output of estimated parameters in for the Haida
  Gwaii AM2 model with constant natural mortality.
  See Figure~\ref{fig:hg-traces} for parameter descriptions.}
\label{fig:hg-constm-pairs}
\end{figure}

%%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<hg.tvm.priors>>=
%% make.priors.posts.plot(hg.am2.tvm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Haida Gwaii AM2 model with time-varying natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:hg-tvm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<hg.tvm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(hg.am2.tvm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the Haida Gwaii
%%   AM2 model with time-varying natural mortality. The MCMC run had chain length
%%   \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:hg-tvm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<hg-tvm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(hg.am2.tvm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the Haida
%%   Gwaii AM2 model with time-varying natural mortality.
%%   See Figure~\ref{fig:hg-traces} for parameter descriptions.}
%% \label{fig:hg-tvm-pairs}
%% \end{figure}

%%------------------------------------------------------------------------------
%% Sensitivity to M MCMC diagnostic plots - AM1
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.am1.constm.priors>>=
make.priors.posts.plot(hg.am1.constm, priors.only = FALSE)
@
\end{center}
\caption{Prior probability distributions (lines) with comparative posterior
  histograms (bars) used in the Haida Gwaii AM1 model with constant natural
  mortality. Parameters $q_k$ represent gears where: $k=1$ is the surface
  survey and $k=2$ is the dive survey. The dotted red lines are the MPD
  estimates.}
\label{fig:hg-am1-constm-priors}
\end{figure}

\begin{figure}[H]
\begin{center}
<<hg.am1.constm.traces, fig.height=8, fig.width=8>>=
make.traces.plot(hg.am1.constm, axis.lab.freq = 200)
@
\end{center}
\caption{Trace plots for MCMC output of estimated parameters for the Haida Gwaii
  AM1 model with constant natural mortality. The MCMC run had chain length
  \Sexpr{mcmc.length}, with
  a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
  The catchability parameter $q_1$ represents the surface survey and $q_2$
  the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
  $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
  follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
\label{fig:hg-am1-constm-traces}
\end{figure}

\begin{figure}[H]
\begin{center}
<<hg-am1-constm-pairs, fig.height=8, fig.width=8>>=
make.pairs.plot(hg.am1.constm)
@
\end{center}
\caption{Pairs plots for MCMC output of estimated parameters in for the Haida
  Gwaii AM1 model with constant natural mortality.
  See Figure~\ref{fig:hg-traces} for parameter descriptions.}
\label{fig:hg-ma1-constm-pairs}
\end{figure}

%%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<hg.am1.tvm.priors>>=
%% make.priors.posts.plot(hg.am2.tvm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Haida Gwaii AM1 model with time-varying natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:hg-am1-tvm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<hg.am1.tvm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(hg.am2.tvm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the Haida Gwaii
%%   AM1 model with time-varying natural mortality. The MCMC run had chain length
%%   \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:hg-am1-tvm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<hg-am1-tvm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(hg.am2.tvm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the Haida
%%   Gwaii AM1 model with time-varying natural mortality.
%%   See Figure~\ref{fig:hg-traces} for parameter descriptions.}
%% \label{fig:hg-am1-tvm-pairs}
%% \end{figure}

%%------------------------------------------------------------------------------
%% Sensitivity to Q 4-panel plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.4panel.qa, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(hg.qa),
                     ylim = c(0, 150),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(hg.qa),
                        ylim = c(0, 12),
                        ind.letter = "b")
make.m.plot(list(hg.qa),
            ylim = c(0, 1.8),
            ind.letter = "c")
make.q.plot(list(hg.qa),
            ylim = c(0, 2),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{hg.qa$ctl$surv.q[3,1]}
  for the Haida Gwaii stock.}
\label{fig:hg-4panel-qa}
\end{figure}

\begin{figure}[H]
\begin{center}
<<hg.4panel.qb, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(hg.qb),
                     ylim = c(0, 150),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(hg.qb),
                        ylim = c(0, 12),
                        ind.letter = "b")
make.m.plot(list(hg.qb),
            ylim = c(0, 1.8),
            ind.letter = "c")
make.q.plot(list(hg.qb),
            ylim = c(0, 2),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{hg.qb$ctl$surv.q[3,1]}
  for the Haida Gwaii stock.}
\label{fig:hg-4panel-qb}
\end{figure}

\begin{figure}[H]
\begin{center}
<<hg.4panel.qc, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(hg.qc),
                     ylim = c(0, 150),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(hg.qc),
                        ylim = c(0, 12),
                        ind.letter = "b")
make.m.plot(list(hg.qc),
            ylim = c(0, 1.8),
            ind.letter = "c")
make.q.plot(list(hg.qc),
            ylim = c(0, 2),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{hg.qc$ctl$surv.q[3,1]}
  for the Haida Gwaii stock.}
\label{fig:hg-4panel-qc}
\end{figure}

%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<prd.4panel.qa, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(pr.qa),
                     ylim = c(0, 150),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(pr.qa),
                        ylim = c(0, 4),
                        ind.letter = "b")
make.m.plot(list(pr.qa),
            ylim = c(0, 1),
            ind.letter = "c")
make.q.plot(list(pr.qa),
            ylim = c(0, 2),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{pr.qa$ctl$surv.q[3,1]}
  for the Prince Rupert District stock.}
\label{fig:prd-4panel-qa}
\end{figure}

\begin{figure}[H]
\begin{center}
<<prd.4panel.qb, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(pr.qb),
                     ylim = c(0, 150),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(pr.qb),
                        ylim = c(0, 4),
                        ind.letter = "b")
make.m.plot(list(pr.qb),
            ylim = c(0, 1),
            ind.letter = "c")
make.q.plot(list(pr.qb),
            ylim = c(0, 2),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{pr.qb$ctl$surv.q[3,1]}
  for the Prince Rupert District stock.}
\label{fig:prd-4panel-qb}
\end{figure}

\begin{figure}[H]
\begin{center}
<<prd.4panel.qc, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(pr.qc),
                     ylim = c(0, 150),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(pr.qc),
                        ylim = c(0, 4),
                        ind.letter = "b")
make.m.plot(list(pr.qc),
            ylim = c(0, 1),
            ind.letter = "c")
make.q.plot(list(pr.qc),
            ylim = c(0, 2),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{pr.qc$ctl$surv.q[3,1]}
  for the Prince Rupert District stock.}
\label{fig:prd-4panel-qc}
\end{figure}

%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<cc.4panel.qa, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(cc.qa),
                     ylim = c(0, 150),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(cc.qa),
                        ylim = c(0, 2.5),
                        ind.letter = "b")
make.m.plot(list(cc.qa),
            ylim = c(0, 1.2),
            ind.letter = "c")
make.q.plot(list(cc.qa),
            ylim = c(0, 1.5),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{cc.qa$ctl$surv.q[3,1]}
  for the Central Coast stock.}
\label{fig:cc-4panel-qa}
\end{figure}

\begin{figure}[H]
\begin{center}
<<cc.4panel.qb, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(cc.qb),
                     ylim = c(0, 150),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(cc.qb),
                        ylim = c(0, 2.5),
                        ind.letter = "b")
make.m.plot(list(cc.qb),
            ylim = c(0, 1.2),
            ind.letter = "c")
make.q.plot(list(cc.qb),
            ylim = c(0, 1.5),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{cc.qb$ctl$surv.q[3,1]}
  for the Central Coast stock.}
\label{fig:cc-4panel-qb}
\end{figure}

\begin{figure}[H]
\begin{center}
<<cc.4panel.qc, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(cc.qc),
                     ylim = c(0, 150),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(cc.qc),
                        ylim = c(0, 2.5),
                        ind.letter = "b")
make.m.plot(list(cc.qc),
            ylim = c(0, 1.2),
            ind.letter = "c")
make.q.plot(list(cc.qc),
            ylim = c(0, 1.5),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{cc.qc$ctl$surv.q[3,1]}
  for the Central Coast stock.}
\label{fig:cc-4panel-qc}
\end{figure}

%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<sog.4panel.qa, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(sog.qa),
                     ylim = c(0, 250),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(sog.qa),
                        ylim = c(0, 2.2),
                        ind.letter = "b")
make.m.plot(list(sog.qa),
            ylim = c(0, 1.5),
            ind.letter = "c")
make.q.plot(list(sog.qa),
            ylim = c(0, 1.5),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{sog.qa$ctl$surv.q[3,1]}
  for the Strait of Georgia stock.}
\label{fig:sog-4panel-qa}
\end{figure}

\begin{figure}[H]
\begin{center}
<<sog.4panel.qb, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(sog.qb),
                     ylim = c(0, 250),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(sog.qb),
                        ylim = c(0, 2.2),
                        ind.letter = "b")
make.m.plot(list(sog.qb),
            ylim = c(0, 1.5),
            ind.letter = "c")
make.q.plot(list(sog.qb),
            ylim = c(0, 1.5),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{sog.qb$ctl$surv.q[3,1]}
  for the Strait of Georgia stock.}
\label{fig:sog-4panel-qb}
\end{figure}

\begin{figure}[H]
\begin{center}
<<sog.4panel.qc, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(sog.qc),
                     ylim = c(0, 250),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(sog.qc),
                        ylim = c(0, 2.2),
                        ind.letter = "b")
make.m.plot(list(sog.qc),
            ylim = c(0, 1.5),
            ind.letter = "c")
make.q.plot(list(sog.qc),
            ylim = c(0, 1.5),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{sog.qc$ctl$surv.q[3,1]}
  for the Strait of Georgia stock.}
\label{fig:sog-4panel-qc}
\end{figure}

%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<wcvi.4panel.qa, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(wcvi.qa),
                     ylim = c(0, 200),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(wcvi.qa),
                        ylim = c(0, 3),
                        ind.letter = "b")
make.m.plot(list(wcvi.qa),
            ylim = c(0, 1.5),
            ind.letter = "c")
make.q.plot(list(wcvi.qa),
            ylim = c(0, 1.5),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{wcvi.qa$ctl$surv.q[3,1]}
  for the WCVI stock.}
\label{fig:wcvi-4panel-qa}
\end{figure}

\begin{figure}[H]
\begin{center}
<<wcvi.4panel.qb, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(wcvi.qb),
                     ylim = c(0, 200),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(wcvi.qb),
                        ylim = c(0, 3),
                        ind.letter = "b")
make.m.plot(list(wcvi.qb),
            ylim = c(0, 1.5),
            ind.letter = "c")
make.q.plot(list(wcvi.qb),
            ylim = c(0, 1.5),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{wcvi.qb$ctl$surv.q[3,1]}
  for the WCVI stock.}
\label{fig:wcvi-4panel-qb}
\end{figure}

\begin{figure}[H]
\begin{center}
<<wcvi.4panel.qc, fig.width = 7.5, fig.height = 7.5>>=
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE))
make.biomass.mcmc.plot(list(wcvi.qc),
                     ylim = c(0, 150),
                      show.bo.line = TRUE,
                     ind.letter = "a")
make.depletion.mcmc.plot(list(wcvi.qc),
                        ylim = c(0, 4),
                        ind.letter = "b")
make.m.plot(list(wcvi.qc),
            ylim = c(0, 1.5),
            ind.letter = "c")
make.q.plot(list(wcvi.qc),
            ylim = c(0, 1.5),
            ind.letter = "d")
@
\end{center}
\caption{q Prior Sensitivity Case: Biomass (a), Depletion (b), Natural Mortality (c) and Survey Q (d) for
  the sensitivity model where the survey q
  standard deviation prior is set to
  \Sexpr{wcvi.qc$ctl$surv.q[3,1]}
  for the WCVI stock.}
\label{fig:wcvi-4panel-qc}
\end{figure}

%%------------------------------------------------------------------------------
%% Age proportion extimates plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.ageest.gear1>>=
make.age.comp.estimates.plot(hg.b, 1)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 1 (other fisheries),
  for Haida Gwaii. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:hg-ageest-gear1}
\end{figure}

\begin{figure}[H]
\begin{center}
<<hg.ageest.gear2>>=
make.age.comp.estimates.plot(hg.b, 2)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 2 (roe seine),
  for Haida Gwaii. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:hg-ageest-gear2}
\end{figure}

\begin{figure}[H]
\begin{center}
<<hg.ageest.gear3>>=
make.age.comp.estimates.plot(hg.b, 3)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 3 (row gillnet),
  for Haida Gwaii. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:hg-ageest-gear3}
\end{figure}

%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<prd.ageest.gear1>>=
make.age.comp.estimates.plot(pr.b, 1)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 1 (other fisheries),
  for the Prince Rupert District. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:prd-ageest-gear1}
\end{figure}

\begin{figure}[H]
\begin{center}
<<prd.ageest.gear2>>=
make.age.comp.estimates.plot(pr.b, 2)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 2 (roe seine),
  for the Prince Rupert District. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:prd-ageest-gear2}
\end{figure}

\begin{figure}[H]
\begin{center}
<<prd.ageest.gear3>>=
make.age.comp.estimates.plot(pr.b, 3)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 3 (roe gillnet),
  for the Prince Rupert District. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:prd-ageest-gear3}
\end{figure}

%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<cc.ageest.gear1>>=
make.age.comp.estimates.plot(cc.b, 1)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 1 (other fisheries),
  for the Central Coast. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:cc-ageest-gear1}
\end{figure}

\begin{figure}[H]
\begin{center}
<<cc.ageest.gear2>>=
make.age.comp.estimates.plot(cc.b, 2)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 2 (roe seine),
  for the Central Coast. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:cc-ageest-gear2}
\end{figure}

\begin{figure}[H]
\begin{center}
<<cc.ageest.gear3>>=
make.age.comp.estimates.plot(cc.b, 3)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 3 (roe gillnet),
  for the Central Coast. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:cc-ageest-gear3}
\end{figure}

%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<sog.ageest.gear1>>=
make.age.comp.estimates.plot(sog.b, 1)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 1 (other fisheries),
  for the Strait of Georgia. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:sog-ageest-gear1}
\end{figure}

\begin{figure}[H]
\begin{center}
<<sog.ageest.gear2>>=
make.age.comp.estimates.plot(sog.b, 2)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 2 (roe seine),
  for the Strait of Georgia. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:sog-ageest-gear2}
\end{figure}

\begin{figure}[H]
\begin{center}
<<sog.ageest.gear3>>=
make.age.comp.estimates.plot(sog.b, 3)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 3 (roe gillnet),
  for the Strait of Georgia. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:sog-ageest-gear3}
\end{figure}

%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<wcvi.ageest.gear1>>=
make.age.comp.estimates.plot(wcvi.b, 1)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 1 (other fisheries),
  for the WCVI. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:wcvi-ageest-gear1}
\end{figure}

\begin{figure}[H]
\begin{center}
<<wcvi.ageest.gear2>>=
make.age.comp.estimates.plot(wcvi.b, 2)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 2 (roe seine),
  for the WCVI. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:wcvi-ageest-gear2}
\end{figure}

\begin{figure}[H]
\begin{center}
<<wcvi.ageest.gear3>>=
make.age.comp.estimates.plot(wcvi.b, 3)
@
\end{center}
\caption{Estimated proportion-at-age versus time for Gear 3 (roe gillnet),
  for the WCVI. The area of each circle reflects the proportion-at-age,
  each column sums to 1, zeros are not shown. Plus group is age-10.}
\label{fig:wcvi-ageest-gear3}
\end{figure}

%%------------------------------------------------------------------------------
%% AM2 retrospective biomass plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.am2.retro.biomass, results='asis', echo=FALSE, fig.height=6.5>>=
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yrs")
make.biomass.retro.mpd.plot(hg.b,
                            base.retro.models[[1]],
                            ylim = c(0, 70),
                            show.bo.line = TRUE,
                            model.names = leg.names)
@
\end{center}
\caption{Retrospective spawning biomass for the
  Haida Gwaii AM2 model.}
\label{fig:hg-retro-biomass}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<prd.am2.retro.biomass, results='asis', echo=FALSE, fig.height=6.5>>=
## Special case for PRD - show 15 yr retro instead of 10
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yr",
               "-11 yrs",
               "-12 yrs",
               "-13 yrs",
               "-14 yrs",
               "-15 yrs")
make.biomass.retro.mpd.plot(pr.b,
                            base.retro.models[[2]],
                            ylim = c(0, 100),
                            show.bo.line = TRUE,
                            model.names = leg.names)
@
\end{center}
\caption{Retrospective spawning biomass for the
  Prince Rupert District AM2 model.}
\label{fig:prd-retro-biomass}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<cc.am2.retro.biomass, results='asis', echo=FALSE, fig.height=6.5>>=
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yrs")
make.biomass.retro.mpd.plot(cc.b,
                            base.retro.models[[3]],
                            ylim = c(0, 80),
                            show.bo.line = TRUE,
                            model.names = leg.names)
@
\end{center}
\caption{Retrospective spawning biomass for the
  Central Coast AM2 model.}
\label{fig:cc-retro-biomass}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<sog.am2.retro.biomass, results='asis', echo=FALSE, fig.height=6.5>>=
make.biomass.retro.mpd.plot(sog.b,
                            base.retro.models[[4]],
                            ylim = c(0, 200),
                            show.bo.line = TRUE,
                            model.names = leg.names)
@
\end{center}
\caption{Retrospective spawning biomass for the
  Strait of Georgia AM2 model.}
\label{fig:sog-retro-biomass}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<wcvi.am2.retro.biomass, results='asis', echo=FALSE, fig.height=6.5>>=
make.biomass.retro.mpd.plot(wcvi.b,
                            base.retro.models[[5]],
                            ylim = c(0, 100),
                            show.bo.line = TRUE,
                            model.names = leg.names)
@
\end{center}
\caption{Retrospective spawning biomass for the
  WCVI AM2 model.}
\label{fig:wcvi-retro-biomass}
\end{figure}

%%------------------------------------------------------------------------------
%% AM1 retrospective biomass plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.am1.retro.biomass, results='asis', echo=FALSE, fig.height=6.5>>=
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yrs")
make.biomass.retro.mpd.plot(hg.am1,
                            am1.retro.models[[1]],
                            ylim = c(0, 90),
                            show.bo.line = TRUE,
                            model.names = leg.names)
@
\end{center}
\caption{Retrospective spawning biomass for the
  Haida Gwaii AM1 model.}
\label{fig:hg-am1-retro-biomass}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<prd.am1.retro.biomass, results='asis', echo=FALSE, fig.height=6.5>>=
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yr",
               "-11 yrs",
               "-12 yrs",
               "-13 yrs",
               "-14 yrs",
               "-15 yrs")
make.biomass.retro.mpd.plot(pr.am1,
                            am1.retro.models[[2]],
                            ylim = c(0, 100),
                            show.bo.line = TRUE,
                            model.names = leg.names)
@
\end{center}
\caption{Retrospective spawning biomass for the
  Prince Rupert District AM1 model.}
\label{fig:prd-am1-retro-biomass}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<cc.am1.retro.biomass, results='asis', echo=FALSE, fig.height=6.5>>=
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yrs")
make.biomass.retro.mpd.plot(cc.am1,
                            am1.retro.models[[3]],
                            ylim = c(0, 90),
                            show.bo.line = TRUE,
                            model.names = leg.names)
@
\end{center}
\caption{Retrospective spawning biomass for the
  Central Coast AM1 model.}
\label{fig:cc-am1-retro-biomass}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<sog.am1.retro.biomass, results='asis', echo=FALSE, fig.height=6.5>>=
make.biomass.retro.mpd.plot(sog.am1,
                            am1.retro.models[[4]],
                            ylim = c(0, 250),
                            show.bo.line = TRUE,
                            model.names = leg.names)
@
\end{center}
\caption{Retrospective spawning biomass for the
  Strait of Georgia AM1 model.}
\label{fig:sog-am1-retro-biomass}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<wcvi.am1.retro.biomass, results='asis', echo=FALSE, fig.height=6.5>>=
make.biomass.retro.mpd.plot(wcvi.am1,
                            am1.retro.models[[5]],
                            ylim = c(0, 100),
                            show.bo.line = TRUE,
                            model.names = leg.names)
@
\end{center}
\caption{Retrospective spawning biomass for the
  WCVI AM1 model.}
\label{fig:wcvi-am1-retro-biomass}
\end{figure}

%%------------------------------------------------------------------------------
%% AM2 retrospective recruitment plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.am2.retro.recr, results='asis', echo=FALSE, fig.height=6.5>>=
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yrs")
make.recr.retro.mpd.plot(hg.b,
                         base.retro.models[[1]],
                         ylim = c(0, 1500),
                         model.names = leg.names)
@
\end{center}
\caption{Retrospective recruitment for the
  Haida Gwaii AM2 model.}
\label{fig:hg-retro-recr}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<prd.am2.retro.recr, results='asis', echo=FALSE, fig.height=6.5>>=
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yr",
               "-11 yrs",
               "-12 yrs",
               "-13 yrs",
               "-14 yrs",
               "-15 yrs")
make.recr.retro.mpd.plot(pr.b,
                         base.retro.models[[2]],
                         ylim = c(0, 1500),
                         model.names = leg.names)
@
\end{center}
\caption{Retrospective recruitment for the
  Prince Rupert District AM2 model.}
\label{fig:prd-retro-recr}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<cc.am2.retro.recr, results='asis', echo=FALSE, fig.height=6.5>>=
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yrs")
make.recr.retro.mpd.plot(cc.b,
                         base.retro.models[[3]],
                         ylim = c(0, 1600),
                         model.names = leg.names)
@
\end{center}
\caption{Retrospective recruitment for the
  Central Coast AM2 model.}
\label{fig:cc-retro-recr}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<sog.am2.retro.recr, results='asis', echo=FALSE, fig.height=6.5>>=
make.recr.retro.mpd.plot(sog.b,
                         base.retro.models[[4]],
                         ylim = c(0, 3000),
                         model.names = leg.names)
@
\end{center}
\caption{Retrospective recruitment for the
  Strait of Georgia AM2 model.}
\label{fig:sog-retro-recr}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<wcvi.am2.retro.recr, results='asis', echo=FALSE, fig.height=6.5>>=
make.recr.retro.mpd.plot(wcvi.b,
                         base.retro.models[[5]],
                         ylim = c(0, 1600),
                         model.names = leg.names)
@
\end{center}
\caption{Retrospective recruitment for the
  WCVI AM2 model.}
\label{fig:wcvi-retro-recr}
\end{figure}

%%------------------------------------------------------------------------------
%% AM1 retrospective recruitment plots
%%------------------------------------------------------------------------------
\begin{figure}[H]
\begin{center}
<<hg.am1.retro.recr, results='asis', echo=FALSE, fig.height=6.5>>=
make.recr.retro.mpd.plot(hg.am1,
                         am1.retro.models[[1]],
                         ylim = c(0, 1800),
                         model.names = leg.names)
@
\end{center}
\caption{Retrospective recruitment for the
  Haida Gwaii AM1 model.}
\label{fig:hg-am1-retro-recr}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<prd.am1.retro.recr, results='asis', echo=FALSE, fig.height=6.5>>=
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yr",
               "-11 yrs",
               "-12 yrs",
               "-13 yrs",
               "-14 yrs",
               "-15 yrs")
make.recr.retro.mpd.plot(pr.am1,
                         am1.retro.models[[2]],
                         ylim = c(0, 2200),
                         model.names = leg.names)
@
\end{center}
\caption{Retrospective recruitment for the
  Prince Rupert District AM1 model.}
\label{fig:prd-am1-retro-recr}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<cc.am1.retro.recr, results='asis', echo=FALSE, fig.height=6.5>>=
leg.names <- c("Base",
               "-1 yr",
               "-2 yrs",
               "-3 yrs",
               "-4 yrs",
               "-5 yrs",
               "-6 yrs",
               "-7 yrs",
               "-8 yrs",
               "-9 yrs",
               "-10 yrs")
make.recr.retro.mpd.plot(cc.am1,
                         am1.retro.models[[3]],
                         ylim = c(0, 1800),
                         model.names = leg.names)
@
\end{center}
\caption{Retrospective recruitment for the
  Central Coast AM1 model.}
\label{fig:cc-am1-retro-recr}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<sog.am1.retro.recr, results='asis', echo=FALSE, fig.height=6.5>>=
make.recr.retro.mpd.plot(sog.am1,
                         am1.retro.models[[4]],
                         ylim = c(0, 6000),
                         model.names = leg.names)
@
\end{center}
\caption{Retrospective recruitment for the
  Strait of Georgia AM1 model.}
\label{fig:sog-am1-retro-recr}
\end{figure}
%%------------------------------------------------------------------------------

\begin{figure}[H]
\begin{center}
<<wcvi.am1.retro.recr, results='asis', echo=FALSE, fig.height=6.5>>=
make.recr.retro.mpd.plot(wcvi.am1,
                         am1.retro.models[[5]],
                         ylim = c(0, 2200),
                         model.names = leg.names)
@
\end{center}
\caption{Retrospective recruitment for the
  WCVI AM1 model.}
\label{fig:wcvi-am1-retro-recr}
\end{figure}

%%------------------------------------------------------------------------------
%% Sensitivity to M MCMC diagnostic plots
%%------------------------------------------------------------------------------
%% \begin{figure}[H]
%% \begin{center}
%% <<hg.constm.priors>>=
%% make.priors.posts.plot(hg.am2.constm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Haida Gwaii AM2 model with constant natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:hg-constm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<hg.constm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(hg.am2.constm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the Haida Gwaii
%%   AM2 model with constant natural mortality. The MCMC run had chain length
%%   \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:hg-constm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<hg-constm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(hg.am2.constm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the Haida
%%   Gwaii AM2 model with constant natural mortality.
%%   See Figure~\ref{fig:hg-traces} for parameter descriptions.}
%% \label{fig:hg-constm-pairs}
%% \end{figure}

%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<hg.tvm.priors>>=
%% make.priors.posts.plot(hg.am2.tvm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Haida Gwaii AM2 model with time-varying natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:hg-tvm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<hg.tvm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(hg.am2.tvm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the Haida Gwaii
%%   AM2 model with time-varying natural mortality. The MCMC run had chain length
%%   \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:hg-tvm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<hg-tvm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(hg.am2.tvm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the Haida
%%   Gwaii AM2 model with time-varying natural mortality.
%%   See Figure~\ref{fig:hg-traces} for parameter descriptions.}
%% \label{fig:hg-tvm-pairs}
%% \end{figure}

%% %%------------------------------------------------------------------------------
%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<prd.constm.priors>>=
%% make.priors.posts.plot(pr.am2.constm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Prince Rupert District AM2 model with constant natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:pr-constm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<prd.constm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(pr.am2.constm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the
%%   Prince Rupert District AM2 model with constant natural mortality.
%%   The MCMC run had chain length \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:prd-constm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<prd-constm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(pr.am2.constm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the
%%   Prince Rupert District AM2 model with constant natural mortality.
%%   See Figure~\ref{fig:hg-traces} for parameter descriptions.}
%% \label{fig:prd-constm-pairs}
%% \end{figure}

%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<prd.tvm.priors>>=
%% make.priors.posts.plot(pr.am2.tvm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Prince Rupert District  AM2 model with
%%   time-varying natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:prd-tvm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<prd.tvm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(pr.am2.tvm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the
%%   Prince Rupert District AM2 model with time-varying natural mortality.
%%   The MCMC run had chain length \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:prd-tvm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<prd-tvm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(pr.am2.tvm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the
%%   Prince Rupert District AM2 model with time-varying natural mortality.
%%   See Figure~\ref{fig:prd-traces} for parameter descriptions.}
%% \label{fig:prd-tvm-pairs}
%% \end{figure}

%% %%------------------------------------------------------------------------------
%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<cc.constm.priors>>=
%% make.priors.posts.plot(cc.am2.constm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Central Coast AM2 model with constant natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:cc-constm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<cc.constm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(cc.am2.constm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the
%%   Central Coast  AM2 model with constant natural mortality.
%%   The MCMC run had chain length \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:cc-constm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<cc-constm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(cc.am2.constm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the
%%   Central Coast  AM2 model with constant natural mortality.
%%   See Figure~\ref{fig:hg-traces} for parameter descriptions.}
%% \label{fig:cc-constm-pairs}
%% \end{figure}

%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<cc.tvm.priors>>=
%% make.priors.posts.plot(cc.am2.tvm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Central Coast   AM2 model with
%%   time-varying natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:cc-tvm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<cc.tvm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(cc.am2.tvm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the
%%   Central Coast  AM2 model with time-varying natural mortality.
%%   The MCMC run had chain length \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:cc-tvm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<cc-tvm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(cc.am2.tvm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the
%%   Central Coast AM2 model with time-varying natural mortality.
%%   See Figure~\ref{fig:prd-traces} for parameter descriptions.}
%% \label{fig:cc-tvm-pairs}
%% \end{figure}

%% %%------------------------------------------------------------------------------
%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<sog.constm.priors>>=
%% make.priors.posts.plot(sog.am2.constm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Strait of Georgia AM2 model with constant natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:sog-constm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<sog.constm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(sog.am2.constm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the
%%   Strait of Georgia AM2 model with constant natural mortality.
%%   The MCMC run had chain length \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:sog-constm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<sog-constm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(sog.am2.constm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the
%%   Strait of Georgia AM2 model with constant natural mortality.
%%   See Figure~\ref{fig:hg-traces} for parameter descriptions.}
%% \label{fig:sog-constm-pairs}
%% \end{figure}

%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<sog.tvm.priors>>=
%% make.priors.posts.plot(sog.am2.tvm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Strait of Georgia AM2 model with
%%   time-varying natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:sog-tvm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<sog.tvm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(sog.am2.tvm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the
%%   Strait of Georgia AM2 model with time-varying natural mortality.
%%   The MCMC run had chain length \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:sog-tvm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<sog-tvm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(sog.am2.tvm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the
%%   Strait of Georgia AM2 model with time-varying natural mortality.
%%   See Figure~\ref{fig:prd-traces} for parameter descriptions.}
%% \label{fig:sog-tvm-pairs}
%% \end{figure}

%% %%------------------------------------------------------------------------------
%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<wcvi.constm.priors>>=
%% make.priors.posts.plot(wcvi.am2.constm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the WCVI AM2 model with constant natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:wcvi-constm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<wcvi.constm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(wcvi.am2.constm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the
%%   WCVI AM2 model with constant natural mortality.
%%   The MCMC run had chain length \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:wcvi-constm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<wcvi-constm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(wcvi.am2.constm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the
%%   WCVI AM2 model with constant natural mortality.
%%   See Figure~\ref{fig:hg-traces} for parameter descriptions.}
%% \label{fig:wcvi-constm-pairs}
%% \end{figure}

%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<wcvi.tvm.priors>>=
%% make.priors.posts.plot(wcvi.am2.tvm, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the WCVI AM2 model with
%%   time-varying natural
%%   mortallity. Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:wcvi-tvm-priors}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<wcvi.tvm.traces, fig.height=8, fig.width=8>>=
%% make.traces.plot(wcvi.am2.tvm, axis.lab.freq = 200)
%% @
%% \end{center}
%% \caption{Trace plots for MCMC output of estimated parameters for the
%%   WCVI AM2 model with time-varying natural mortality.
%%   The MCMC run had chain length \Sexpr{mcmc.length}, with
%%   a sample taken at every \Sexpr{mcmc.samp.freq}th iteration.
%%   The catchability parameter $q_1$ represents the surface survey and $q_2$
%%   the dive survey. Parameters $\hat{a}_k$ (selectivity-at-age-50\%), and
%%   $\hat{\gamma}_k$ (selectivity standard deviation-at-50\%) represent gears as
%%   follows: $k=1$: Other fisheries, $k=2$: Roe seine, $k=3$: Gillnet roe.}
%% \label{fig:wcvi-tvm-traces}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<wcvi-tvm-pairs, fig.height=8, fig.width=8>>=
%% make.pairs.plot(wcvi.am2.tvm)
%% @
%% \end{center}
%% \caption{Pairs plots for MCMC output of estimated parameters in for the
%%   WCVI AM2 model with time-varying natural mortality.
%%   See Figure~\ref{fig:prd-traces} for parameter descriptions.}
%% \label{fig:wcvi-tvm-pairs}
%% \end{figure}

%%------------------------------------------------------------------------------
%%------------------------------------------------------------------------------

%%------------------------------------------------------------------------------
%% Sensitivity to Q MCMC diagnostic plots
%%------------------------------------------------------------------------------
%% \begin{figure}[H]
%% \begin{center}
%% <<hg.qa>>=
%% make.priors.posts.plot(hg.qa, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Haida Gwaii AM1 model with the standard
%%   deviation on survey q set to \Sexpr{hg.qa$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:hg-qa}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<hg.qb>>=
%% make.priors.posts.plot(hg.qb, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Haida Gwaii AM1 model with the standard
%%   deviation on survey q set to \Sexpr{hg.qb$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:hg-qb}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<hg.qc>>=
%% make.priors.posts.plot(hg.qc, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Haida Gwaii AM1 model with the standard
%%   deviation on survey q set to \Sexpr{hg.qc$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:hg-qc}
%% \end{figure}

%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<prd.qa>>=
%% make.priors.posts.plot(pr.qa, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Prince Rupert District AM1 model with the standard
%%   deviation on survey q set to \Sexpr{pr.qa$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:pr-qa}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<prd.qb>>=
%% make.priors.posts.plot(pr.qb, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Prince Rupert District AM1 model with the standard
%%   deviation on survey q set to \Sexpr{pr.qb$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:pr-qb}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<prd.qc>>=
%% make.priors.posts.plot(pr.qc, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Prince Rupert District AM1 model with the standard
%%   deviation on survey q set to \Sexpr{pr.qc$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:pr-qc}
%% \end{figure}

%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<cc.qa>>=
%% make.priors.posts.plot(cc.qa, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Central Coast AM1 model with the standard
%%   deviation on survey q set to \Sexpr{cc.qa$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:cc-qa}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<cc.qb>>=
%% make.priors.posts.plot(cc.qb, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Central Coast AM1 model with the standard
%%   deviation on survey q set to \Sexpr{cc.qb$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:cc-qb}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<cc.qc>>=
%% make.priors.posts.plot(cc.qb, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Central Coast AM1 model with the standard
%%   deviation on survey q set to \Sexpr{cc.qb$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:cc-qb}
%% \end{figure}

%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<sog.qa>>=
%% make.priors.posts.plot(sog.qa, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Strait of Georgia AM1 model with the standard
%%   deviation on survey q set to \Sexpr{sog.qa$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:sog-qa}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<sog.qb>>=
%% make.priors.posts.plot(sog.qb, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Strait of Georgia AM1 model with the standard
%%   deviation on survey q set to \Sexpr{sog.qb$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:sog-qb}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<sog.qc>>=
%% make.priors.posts.plot(sog.qc, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the Strait of Georgia AM1 model with the standard
%%   deviation on survey q set to \Sexpr{sog.qc$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:sog-qc}
%% \end{figure}

%% %%------------------------------------------------------------------------------

%% \begin{figure}[H]
%% \begin{center}
%% <<wcvi.qa>>=
%% make.priors.posts.plot(wcvi.qa, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the WCVI AM1 model with the standard
%%   deviation on survey q set to \Sexpr{wcvi.qa$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:wcvi-qa}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<wcvi.qb>>=
%% make.priors.posts.plot(wcvi.qb, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the WCVI AM1 model with the standard
%%   deviation on survey q set to \Sexpr{wcvi.qb$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:wcvi-qb}
%% \end{figure}

%% \begin{figure}[H]
%% \begin{center}
%% <<wcvi.qc>>=
%% make.priors.posts.plot(wcvi.qc, priors.only = FALSE)
%% @
%% \end{center}
%% \caption{Prior probability distributions (lines) with comparative posterior
%%   histograms (bars) used in the WCVI AM1 model with the standard
%%   deviation on survey q set to \Sexpr{wcvi.qc$ctl$surv.q[3,1]}.
%%   Parameters $q_k$ represent gears where: $k=1$ is the surface
%%   survey and $k=2$ is the dive survey. The dotted red lines are the MPD
%%   estimates.}
%% \label{fig:wcvi-qc}
%% \end{figure}







% %% REFERENCE POINT PLOT
% \begin{figure}[H]
% \begin{center}
% <<ref.points, fig.height=5,fig.width=8>>=
% make.reference.points.plot(base.model,
%                            ref.pts = c("bo",
%                                        "bmsy",
%                                        "msy",
%                                        "umsy"))
% @
% \end{center}
% \caption{Posterior reference points for the Reference Case. Bars represent
%   \Sexpr{mcmc.ci} credible intervals. MSY, B\subscr{0}, and B\subscr{MSY}
%   values are in thousands of tonnes.}
% \label{fig:ref-points}
% \end{figure}
% 
% 
% 
% 
% 
% 
% 
% %%------------------------------------------------------------------------------
% %% FISHING MORTALITY PLOT
% \begin{figure}[H]
% \begin{center}
% <<F, fig.height=5, fig.width=8>>=
% make.fishing.mort.mcmc.plot(base.model,
%                             ylim = c(0, 0.5),
%                             opacity = 20,
%                             col = "black")
% @
% \end{center}
% \caption{Fishing mortality for the Reference Case. The shaded area represents
%   the \Sexpr{mcmc.ci} credible interval.}
% \label{fig:f-mort}
% 
% %%------------------------------------------------------------------------------
% %% RELATIVE SPAWNING BIOMASS PLOT
% \begin{center}
% <<depletion, fig.height=5, fig.width=8>>=
% make.rel.biomass.mcmc.plot(base.model,
%                            opacity = 20)
% @
% \end{center}
% \caption{Relative median posterior spawning biomass for the Reference Case.
%   The shaded area represents the \Sexpr{mcmc.ci} credible interval.}
% \label{fig:depletion}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %%%%%%%%%%%%%%%%%%%%%%%
% %% SENSITIVITY PLOTS
% %% Survey indices
% 
% \begin{figure}[H]
% \begin{center}
% <<sens-sig-indices, fig.height=9, fig.width=8>>=
% s.yr <- 1996
% e.yr <- 2014
% old.par <- par(no.readonly = TRUE)
% layout(matrix(c(1,2,3,4), 2, 2, byrow = TRUE))
% make.index.fit.plot(c(base.model, sens.models.1),
%                     model.names = c(base.model.name, sens.model.names.1),
%                     leg = "bottomright",
%                     start.yr = s.yr,
%                     end.yr = e.yr,
%                     ind = 1,
%                     ylim = c(0,20),
%                     ind.letter = "a")
% make.index.fit.plot(c(base.model, sens.models.1),
%                     start.yr = s.yr,
%                     end.yr = e.yr,
%                     ind = 2,
%                     ylim = c(0,20),
%                     ind.letter = "b")
% make.index.fit.plot(c(base.model, sens.models.1),
%                     start.yr = s.yr,
%                     end.yr = e.yr,
%                     ind = 3,
%                     ylim = c(0,20),
%                     ind.letter = "c")
% make.index.fit.plot(c(base.model, sens.models.1),
%                     start.yr = s.yr,
%                     end.yr = e.yr,
%                     ind = 4,
%                     ylim = c(0,20),
%                     ind.letter = "d")
% par(old.par)
% @
% \end{center}
% \caption{MPD Index fits for (a) QSSS, (b) HSMAS, (c) HSSS, (d) WCVISS for models
%   examining sensitivity to the $\sigma$ parameter.}
% \label{fig:sens-sig-indices}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% Sigma sensitivity - Spawning biomass
% 
% \begin{figure}[H]
% \begin{center}
% <<sens-sig-biomass, fig.height=5, fig.width=8>>=
% make.biomass.mcmc.plot(c(base.model, sens.models.1),
%                        model.names = c(base.model.name, sens.model.names.1),
%                        ylim = c(0, 1300),
%                        opacity = 20,
%                        leg = "topright")
% @
% \end{center}
% \caption{Estimated median spawning biomass with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the $\sigma$ parameter. Points and bars
%   represent the estimates of $B_0$ with \Sexpr{mcmc.ci} credible interval.}
% \label{fig:sens-sig-biomass}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% Sigma sensitivity - Recruitment
% \begin{figure}[H]
% \begin{center}
% <<sens-sig-recruitment, fig.height=9, fig.width=8>>=
% old.par <- par(no.readonly = TRUE)
% layout(matrix(c(1, 2), 2, 1, byrow = FALSE))
% make.recr.mcmc.plot(c(base.model, sens.models.1),
%                     c(base.model.name, sens.model.names.1),
%                     type = 1,
%                     ylim = c(0, 27),
%                     offset = 0.1,
%                     show.median = TRUE,
%                     show.mean = TRUE,
%                     leg = "topright",
%                     ind.letter = "a")
% make.recr.mcmc.plot(c(base.model, sens.models.1),
%                     c(base.model.name, sens.model.names.1),
%                     type = 2,
%                     ylim = c(-1, 4),
%                     offset = 0.1,
%                     ind.letter = "b")
% par(old.par)
% @
% \end{center}
% \caption{Estimated recruitment (a) and recruitment deviations (b) with
%   \Sexpr{mcmc.ci} credible intervals, for models examining sensitivity to the $\sigma$
%   parameter.}
% \label{fig:sens-sig-recruitment}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% Tau sensitivity - Recruitment
% \begin{figure}[H]
% \begin{center}
% <<sens-tau-recruitment, fig.height=9, fig.width=8>>=
% old.par <- par(no.readonly = TRUE)
% layout(matrix(c(1, 2), 2, 1, byrow = FALSE))
% make.recr.mcmc.plot(c(base.model, sens.models.2),
%                     c(base.model.name, sens.model.names.2),
%                     type = 1,
%                     ylim = c(0, 27),
%                     offset = 0.1,
%                     append.base.txt = ", Tau = 0.8",
%                     show.median = TRUE,
%                     show.mean = TRUE,
%                     leg = "topright",
%                     ind.letter = "a")
% make.recr.mcmc.plot(c(base.model, sens.models.2),
%                     c(base.model.name, sens.model.names.2),
%                     type = 2,
%                     ylim = c(-1, 4),
%                     offset = 0.1,
%                     ind.letter = "b")
% par(old.par)
% @
% \end{center}
% \caption{Estimated recruitment (a) and recruitment deviations (b) with
%   \Sexpr{mcmc.ci} credible intervals, for models examining sensitivity to the $\tau$
%   parameter.}
% \label{fig:sens-tau-recruitment}
% \end{figure}
% 
% 
% %%------------------------------------------------------------------------------
% %% Tau sensitivity - Spawning Biomass
% \begin{figure}[H]
% \begin{center}
% <<sens-tau-biomass, fig.height=5, fig.width=8>>=
% make.biomass.mcmc.plot(c(base.model, sens.models.2),
%                        model.names = c(base.model.name, sens.model.names.2),
%                        ylim = c(0, 1300),
%                        opacity = 20,
%                        append.base.txt = ", Tau = 0.8",
%                        leg = "topright")
% @
% \end{center}
% \caption{Estimated median spawning biomass with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the $\tau$ parameter. Points and bars
%   represent the estimates of $B_0$ with \Sexpr{mcmc.ci} credible interval.}
% \label{fig:sens-tau-biomass}
% 
% %%------------------------------------------------------------------------------
% %% Tau sensitivity - Relative Spawning Biomass
% \begin{center}
% <<sens-tau-depletion, fig.height=5,fig.width=8>>=
% make.rel.biomass.mcmc.plot(c(base.model, sens.models.2),
%                            c(base.model.name, sens.model.names.2),
%                            append.base.txt = ", Tau = 0.8",
%                            opacity = 20,
%                            leg = "topright")
% @
% \end{center}
% \caption{Estimated relative median spawning biomass with \Sexpr{mcmc.ci} credible
%   intervals, for models examining sensitivity to the $\tau$ parameter.}
% \label{fig:sens-tau-depletion}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% Steepness sensitivity - Relative Spawning Biomass
% \begin{figure}[H]
% \begin{center}
% <<sens-h-biomass, fig.height=5,fig.width=8>>=
% make.biomass.mcmc.plot(c(base.model, sens.models.3),
%                        model.names = c(base.model.name, sens.model.names.3),
%                        ylim = c(0, 1300),
%                        opacity = 20,
%                        leg = "topright")
% @
% \end{center}
% \caption{Estimated median spawning biomass with \Sexpr{mcmc.ci} credible intervals,
%   for models examining sensitivity to the steepness parameter. Points and bars
%   represent the estimates of $B_0$ with \Sexpr{mcmc.ci} credible interval.}
% \label{fig:sens-h-biomass}
% 
% \begin{center}
% <<sens-h-recruitment, fig.height=5,fig.width=8>>=
% make.recr.mcmc.plot(c(base.model, sens.models.3),
%                     c(base.model.name, sens.model.names.3),
%                     type = 1,
%                     ylim = c(0, 27),
%                     offset = 0.1,
%                     leg = "topleft")
% @
% \end{center}
% \vspace{-3mm}
% \caption{Estimated median recruitment with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the steepness parameter.}
% \label{fig:sens-h-recruitment}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% M sensitivity - Relative Spawning Biomass
% \begin{figure}[H]
% \begin{center}
% <<sens-msd-biomass, fig.height=5,fig.width=8>>=
% make.biomass.mcmc.plot(c(base.model, sens.models.4),
%                        model.names = c(base.model.name, sens.model.names.4),
%                        ylim = c(0, 1300),
%                        opacity = 20,
%                        leg = "topright")
% @
% \end{center}
% \caption{Estimated median spawning biomass with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the standard deviation of the natural mortality
%   parameter. Points and bars represent the estimates of $B_0$ with
%   \Sexpr{mcmc.ci} credible interval.}
% \label{fig:sens-msd-biomass}
% 
% \begin{center}
% <<sens-msd-recruitment, fig.height=5,fig.width=8>>=
% make.recr.mcmc.plot(c(base.model, sens.models.4),
%                     c(base.model.name, sens.model.names.4),
%                     type = 1,
%                     ylim = c(0, 27),
%                     offset = 0.1,
%                     leg = "topleft")
% @
% \end{center}
% \vspace{-3mm}
% \caption{Estimated median recruitment with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the standard deviation of the natural
%   mortality parameter.}
% \label{fig:sens-msd-recruitment}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% M sensitivity 2 - Relative Spawning Biomass
% \begin{figure}[H]
% \begin{center}
% <<sens-m-biomass, fig.height=5,fig.width=8>>=
% make.biomass.mcmc.plot(c(base.model, sens.models.5),
%                        model.names = c(base.model.name, sens.model.names.5),
%                        ylim = c(0, 1300),
%                        opacity = 20,
%                        leg = "topright")
% @
% \end{center}
% \caption{Estimated median spawning biomass with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the natural mortality parameter. Points and
%   bars represent the estimates of $B_0$ with \Sexpr{mcmc.ci} credible interval.}
% \label{fig:sens-m-biomass}
% 
% \begin{center}
% <<sens-m-recruitment, fig.height=5,fig.width=8>>=
% make.recr.mcmc.plot(c(base.model, sens.models.5),
%                     c(base.model.name, sens.model.names.5),
%                     type = 1,
%                     ylim = c(0, 27),
%                     offset = 0.1,
%                     leg = "topleft")
% @
% \end{center}
% \vspace{-3mm}
% \caption{Estimated median recruitment with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the the natural mortality parameter.}
% \label{fig:sens-m-recruitment}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% Q sensitivity - Relative Spawning Biomass
% \begin{figure}[H]
% \begin{center}
% <<sens-q-biomass, fig.height=5,fig.width=8>>=
% make.biomass.mcmc.plot(c(base.model, sens.models.6),
%                        model.names = c(base.model.name, sens.model.names.6),
%                        ylim = c(0, 1300),
%                        opacity = 20,
%                        leg = "topright")
% @
% \end{center}
% \caption{Estimated median spawning biomass with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the catchability parameter. Points and
%   bars represent the estimates of $B_0$ with \Sexpr{mcmc.ci} credible interval.}
% \label{fig:sens-q-biomass}
% 
% \begin{center}
% <<sens-q-recruitment, fig.height=5,fig.width=8>>=
% make.recr.mcmc.plot(c(base.model, sens.models.7),
%                     c(base.model.name, sens.model.names.7),
%                     type = 1,
%                     ylim = c(0, 27),
%                     offset = 0.1,
%                     leg = "topleft")
% @
% \end{center}
% \vspace{-3mm}
% \caption{Estimated median recruitment with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the the catchability parameter.}
% \label{fig:sens-q-recruitment}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% Q sensitivity 2 - Relative Spawning Biomass
% \begin{figure}[H]
% \begin{center}
% <<sens-qsd-biomass, fig.height=5,fig.width=8>>=
% make.biomass.mcmc.plot(c(base.model, sens.models.7),
%                        model.names = c(base.model.name, sens.model.names.7),
%                        ylim = c(0, 1600),
%                        opacity = 20,
%                        leg = "topright")
% @
% \end{center}
% \caption{Estimated median spawning biomass with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the catchability standard deviation parameter.
%   Points and bars represent the estimates of $B_0$ with \Sexpr{mcmc.ci} credible
%   interval.}
% \label{fig:sens-qsd-biomass}
% 
% \begin{center}
% <<sens-qsd-recruitment, fig.height=5,fig.width=8>>=
% make.recr.mcmc.plot(c(base.model, sens.models.7),
%                     c(base.model.name, sens.model.names.7),
%                     type = 1,
%                     ylim = c(0, 27),
%                     offset = 0.1,
%                     leg = "topleft")
% @
% \end{center}
% \vspace{-3mm}
% \caption{Estimated median recruitment with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to the the catchability standard deviation
%   parameter.}
% \label{fig:sens-qsd-recruitment}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% Trawl selectivity sensitivity - selectivity
% \begin{figure}[H]
% \begin{center}
% <<sens-trawlsel-selex, fig.height=5,fig.width=8>>=
% make.selex.comparison.plot(c(base.model,
%                              sens.models.8),
%                            c(base.model.name,
%                              sens.model.names.8),
%                            ind = 1,
%                            leg = "bottomright")
% @
% \end{center}
% \caption{Trawl selectivity for models examining sensitivity to trawl
%   selectivity.}
% \label{fig:sens-trawlsel-selex}
% 
% \begin{center}
% <<sens-trawl-selex-biomass, fig.height=5,fig.width=8>>=
% make.biomass.mcmc.plot(c(base.model,
%                          sens.models.8),
%                        model.names = c(base.model.name,
%                                        sens.model.names.8),
%                        ylim = c(0, 1300),
%                        opacity = 20,
%                        leg = "topright")
% @
% \end{center}
% \caption{Estimated median spawning biomass with \Sexpr{mcmc.ci} credible intervals, for
%   models examining sensitivity to trawl selectivity. Points and bars represent
%   the estimates of $B_0$ with \Sexpr{mcmc.ci} credible interval.}
% \label{fig:sens-trawl-selex-biomass}
% \end{figure}
% 
% %%------------------------------------------------------------------------------
% %% Trawl selectivity sensitivity - reference points
% \begin{figure}[htp]
% \begin{center}
% <<sens-trawl-selex-refpoints, fig.height=5,fig.width=8>>=
% make.reference.points.plot(c(base.model,
%                              sens.models.8))
% @
% \end{center}
% \caption{Posterior reference points for models examining sensitivity to trawl
%   selectivity. Bars represent \Sexpr{mcmc.ci} credible intervals. 1 =
%   \Sexpr{base.model.name}, 2 = \Sexpr{sens.model.names.8[1]}, 3 =
%   \Sexpr{sens.model.names.8[2]}. MSY-based reference points are in thousands
%   of tonnes.}
% \label{fig:sens-trawl-selex-ref-points}
% \end{figure}
% 
% \clearpage
